// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { decodeHexF64 } from "../codec";
import type {
  CancelRequest,
  CancelResponse,
  CloseDatasetRequest,
  CloseDatasetResponse,
  DescribeRequest,
  DescribeResponse,
  OpenDatasetRequest,
  OpenDatasetResponse,
  SkpError,
  ViewportQueryRequest,
  ViewportQueryResponse,
} from "../types";
import { FILTER_DIALECT_DUCKDB_EXPR_0, SKP_VERSION } from "../types";
import { assertExactKeys } from "../../testUtils/assertExactKeys";
import { crsProvenanceLine, displayConventionLine, sessionStatementLine } from "../../admission/describeSummaryText";

/**
 * One canonical request/response per command, read by **both** the Rust host
 * (`protocol/skp/tests/fixtures.rs`) and this client, generated by neither -- the same discipline
 * `renderer/tests/data/manifest-key-sets.json` already establishes for ADR-017: a reader and a
 * writer with separate hand-maintained tables can each stay green while disagreeing with each
 * other about the wire shape. This file is where they agree.
 */
const FIXTURE_DIR = path.resolve(__dirname, "../../../../../protocol/skp/tests/data");

function loadFixture<T>(name: string): T {
  const file = path.join(FIXTURE_DIR, `${name}.json`);
  return JSON.parse(fs.readFileSync(file, "utf-8")) as T;
}

/**
 * `protocol/skp`'s own `fixtures.rs` gets full-shape coverage for free: it deserializes each
 * fixture into a `#[serde(deny_unknown_fields)]` struct and re-serializes it, so an extra or
 * missing field fails that test regardless of whether any individual assertion names it.
 * TypeScript's `interface`s are erased at runtime and give this client no equivalent for free
 * (S10, reviewer) -- the per-field `expect`s below this point in the file only catch drift in
 * whichever field they happen to name. `assertExactKeys` (`../../testUtils/assertExactKeys`)
 * closes that gap the same way `renderer/tests/data/manifest-key-sets.json` closes it for the
 * bundle manifest: check the fixture's actual keys against the exact set `types.ts` declares for
 * that shape. Shared with `console/renderTruth.test.ts` (NEXT-CUT.md P1) rather than redefined.
 */

describe("SKP v0 shared fixtures", () => {
  it("open_dataset request/response", () => {
    const req = loadFixture<OpenDatasetRequest>("v0-open_dataset-request");
    assertExactKeys(
      req,
      ["skp", "path", "cancel_key", "crs_assertion", "identity"],
      "open_dataset request"
    );
    expect(req.skp).toBe(SKP_VERSION);
    expect(typeof req.path).toBe("string");
    expect(typeof req.cancel_key).toBe("string");
    expect(req.crs_assertion).toBeNull(); // skp/0.2: absent assertion is `null`, never omitted
    expect(req.identity).toBeNull(); // skp/0.2: absent declaration is `null`, never omitted

    const res = loadFixture<OpenDatasetResponse>("v0-open_dataset-response");
    assertExactKeys(res, ["dataset"], "open_dataset response");
    expect(res.dataset).toMatch(/^ds_[0-9a-f]{32}$/);
  });

  it("open_dataset request with crs_assertion and identity present (skp/0.2)", () => {
    const req = loadFixture<OpenDatasetRequest>(
      "v0-open_dataset-request-with-crs_assertion-and-identity"
    );
    assertExactKeys(
      req,
      ["skp", "path", "cancel_key", "crs_assertion", "identity"],
      "open_dataset request (with crs_assertion and identity)"
    );
    expect(req.skp).toBe(SKP_VERSION);
    expect(req.crs_assertion).not.toBeNull();
    assertExactKeys(
      req.crs_assertion,
      ["identifier", "definition_json"],
      "open_dataset request .crs_assertion"
    );
    expect(req.crs_assertion!.identifier).toBe("EPSG:2056");
    expect(req.identity).not.toBeNull();
    assertExactKeys(req.identity, ["column"], "open_dataset request .identity");
    expect(req.identity!.column).toBe("parcel_key");
  });

  it("describe request/response, including the two brief corrections (extent, row_count)", () => {
    const req = loadFixture<DescribeRequest>("v0-describe-request");
    assertExactKeys(req, ["skp", "dataset"], "describe request");
    expect(req.dataset).toMatch(/^ds_[0-9a-f]{32}$/);

    const res = loadFixture<DescribeResponse>("v0-describe-response");
    assertExactKeys(
      res,
      ["source", "crs", "geometry", "identity", "schema", "covering_bbox", "row_count", "extent", "license", "sanity"],
      "describe response"
    );
    assertExactKeys(res.source, ["path_display", "geoparquet_version"], "describe response .source");
    assertExactKeys(
      res.crs,
      [
        "identifier",
        "definition_json",
        "source",
        "asserted_by",
        "asserted_at",
        "definition_provenance",
        "axis_order",
        "axis_normalization",
        // skp/0.3, Brief A boundary 9
        "provenance",
        "axis_provenance",
        "display_convention",
      ],
      "describe response .crs"
    );
    expect(res.crs.definition_provenance).toBeNull(); // this fixture's source is "file"
    assertExactKeys(
      res.geometry,
      ["column", "encoding", "coordinate_layout", "frame"],
      "describe response .geometry"
    );
    assertExactKeys(
      res.identity,
      ["source", "uniqueness", "verified_rows", "max_value", "js_exact", "class", "session_statement"],
      "describe response .identity"
    );
    for (const [i, field] of res.schema.entries()) {
      assertExactKeys(field, ["name", "arrow_type", "nullable"], `describe response .schema[${i}]`);
    }
    assertExactKeys(res.row_count, ["basis", "value"], "describe response .row_count");
    assertExactKeys(res.extent, ["basis", "value"], "describe response .extent");
    assertExactKeys(
      res.license,
      ["license", "attribution", "redistribution", "declares_anything"],
      "describe response .license"
    );

    expect(res.crs.identifier).toBe("EPSG:2056");
    expect(res.crs.source).toBe("file");
    expect(res.geometry.frame).toBe("authoritative-project-crs");
    // C1: no bounds() accessor exists on the engine -- extent is honestly not established at open.
    expect(res.extent.basis).toBe("not-established-at-open");
    expect(res.extent.value).toBeNull();
    // C2: row_count carries its basis, never a bare integer.
    expect(res.row_count.basis).toBe("identity-uniqueness-scan-full-file");
    expect(res.row_count.value).toBe("100000");
    expect(res.identity.js_exact).toBe(true);
    // skp/0.3, Brief A boundary 9: the four additions, in their unpopulated shape on a
    // file-declared, natively-identified dataset.
    assertExactKeys(res.sanity, ["level", "reason"], "describe response .sanity");
    expect(res.crs.provenance).toBe("crs:declared");
    expect(res.crs.axis_provenance).toBe("axis:declared");
    expect(res.crs.display_convention).toBeNull(); // not a degrees dataset
    expect(res.identity.class).toBe("native");
    expect(res.identity.session_statement).toBeNull();
    // A sanity check convicts, never confirms: "none" is *not checked*, and no string here says a
    // file passed, is valid, or was verified (Brief A settled boundary 2).
    expect(res.sanity.level).toBe("none");
    expect(res.sanity.reason).toMatch(/not checked/i);
    expect(res.sanity.reason).not.toMatch(/passed|valid|verified/i);
  });

  // Mutation: add a generation member to the describe response shape and populate the fixture.
  // Expected failure: "describe response for a session-ordinal dataset carries the tier, its
  // statement and the P2-held display convention -- and no generation value" fails its A2 sweep.
  it("describe response for a session-ordinal dataset carries the tier, its statement and the " +
    "P2-held display convention -- and no generation value (skp/0.3, Brief A boundary 9)", () => {
    const res = loadFixture<DescribeResponse>("v0-describe-response-session-ordinal");
    expect(res.identity.class).toBe("session-ordinal");
    expect(res.identity.source).toBe("session-ordinal:file_row_number");
    expect(res.identity.uniqueness).toBe("by-construction-within-generation");
    // Nothing was counted, so nothing is claimed -- `null` is the honest answer, not a gap.
    expect(res.identity.verified_rows).toBeNull();
    expect(res.identity.js_exact).toBeNull();
    expect(res.identity.session_statement).toBeTruthy();
    // A1: the statement says the identity does not outlive the open. It never says the open read
    // one snapshot, and no string on this response does.
    expect(res.identity.session_statement).toContain("does not survive this open");
    // Cross-module seam, real shape (round 16, item 1; reviewer gate attempt 1, B1): the two
    // describeSummaryText.ts render functions are pass-throughs of this fixture's own bytes, not a
    // retyped sentence. `res.identity.session_statement` is asserted non-null above (`toBeTruthy`);
    // this fixture's own JSON carries it at
    // `protocol/skp/tests/data/v0-describe-response-session-ordinal.json:29`.
    expect(sessionStatementLine(res.identity)).toBe(res.identity.session_statement);
    expect(crsProvenanceLine(res.crs)).toBe("crs:format-default, axis:declared");
    // The equirectangular sentence travels over the wire from the Rust constant. This test asserts
    // its bytes are carried; it is deliberately the only place in this frontend that quotes it, and
    // it quotes it from the fixture rather than retyping it into rendering code.
    expect(res.crs.display_convention).toBe(
      "no coordinate value is transformed; the display convention is equirectangular"
    );
    // Cross-module seam, real shape (ADR-013 display statement piece): displayConventionLine is a
    // pass-through of this fixture's own bytes, not a retyped sentence -- res.crs.display_convention
    // is asserted verbatim above.
    //
    // RECORDED MUTATION for this seam assertion: displayConventionLine mutated to
    // `return null;` unconditionally. Observed failure (applied and reverted, worker run):
    // "AssertionError: expected null to be 'no coordinate value is transformed; t…' // Object.is
    // equality -- Expected: \"no coordinate value is transformed; the display convention is
    // equirectangular\" -- Received: null" at this file's
    // `expect(displayConventionLine(res.crs)).toBe(res.crs.display_convention)` line.
    expect(displayConventionLine(res.crs)).toBe(res.crs.display_convention);
    expect(res.crs.provenance).toBe("crs:format-default");

    // **A2 on the wire**: no generation value anywhere on this response. The word itself is not
    // banned and cannot be -- ADR-016 §6's record value is literally
    // `by-construction-within-generation`, a label for a basis and not a value -- so the assertion
    // is that `dataset_session_generation` appears nowhere and every occurrence of the word is that
    // one label.
    const text = JSON.stringify(res);
    expect(text).not.toContain("dataset_session_generation");
    expect(text.match(/generation/g)?.length ?? 0).toBe(
      text.match(/by-construction-within-generation/g)?.length ?? 0
    );
    expect(text.toLowerCase()).not.toContain("snapshot");
  });

  // Mutation: drop the `detail` field from the source_changed fixture. Expected failure:
  // "the three new typed refusals carry their code and detail (skp/0.3)" fails -- a client that
  // must clear residency on a specific component change would have only prose to read.
  it("the three new typed refusals carry their code and detail (skp/0.3)", () => {
    const changed = loadFixture<SkpError>("v0-error-source_changed");
    expect(changed.code).toBe("engine.source_changed");
    // The detail names every descriptor component that differed, not the first one.
    expect(changed.fields.detail).toBe("{size, mtime, footer-length, footer-hash}");
    // The message carries boundary 4's limitation in that boundary's own words, and claims nothing
    // more (A1).
    expect(changed.message).toContain("does not establish snapshot consistency");
    expect(changed.message).toContain("cannot detect every in-place modification");
    expect(changed.message).not.toContain("reads one snapshot");

    for (const name of [
      "v0-error-identity_ordinal_partitioned_unsupported",
      "v0-error-internal_inconsistency",
    ]) {
      const err = loadFixture<SkpError>(name);
      assertExactKeys(err, ["code", "message", "fields"], name);
      expect(err.code.startsWith("engine.")).toBe(true);
      expect(err.fields.detail).toBeDefined();
    }
  });

  it("describe response with a caller-asserted CRS carries a populated definition_provenance " +
    "(SF10, reviewer gate, admission-remediation cut)", () => {
    const res = loadFixture<DescribeResponse>("v0-describe-response-caller-asserted");
    assertExactKeys(
      res.crs,
      [
        "identifier",
        "definition_json",
        "source",
        "asserted_by",
        "asserted_at",
        "definition_provenance",
        "axis_order",
        "axis_normalization",
        // skp/0.3, Brief A boundary 9
        "provenance",
        "axis_provenance",
        "display_convention",
      ],
      "describe response (caller-asserted) .crs"
    );
    expect(res.crs.source).toBe("caller_asserted");
    expect(res.crs.asserted_by).toBe("os-user chris");
    expect(res.crs.asserted_at).toBe("2026-08-18T00:00:00Z");
    expect(res.crs.definition_provenance).toBe("catalog:epsg-2056@sha256:254016888ff4");
  });

  it("viewport_query request/response, with bbox edges as hex, never JSON numbers", () => {
    const req = loadFixture<ViewportQueryRequest>("v0-viewport_query-request");
    assertExactKeys(
      req,
      ["skp", "dataset", "bbox", "bbox_crs", "limit", "filter"],
      "viewport_query request"
    );
    expect(req.bbox).not.toBeNull();
    assertExactKeys(req.bbox, ["xmin", "ymin", "xmax", "ymax"], "viewport_query request .bbox");
    expect(req.bbox!.xmin).toBe("0000000000000000");
    expect(decodeHexF64(req.bbox!.xmin)).toBe(0);
    expect(decodeHexF64(req.bbox!.xmax)).toBe(1);
    expect(decodeHexF64(req.bbox!.ymax)).toBe(2);
    expect(req.bbox_crs).toBeNull(); // declares "the dataset's own CRS" (SKP-V0.md §1)
    expect(req.limit).toBe("5000");
    expect(req.filter).toBeNull(); // skp/0.1: absent filter is `null`, never omitted

    const res = loadFixture<ViewportQueryResponse>("v0-viewport_query-response");
    assertExactKeys(res, ["stream", "expires_in_ms"], "viewport_query response");
    expect(res.stream).toMatch(/^sh_[0-9a-f]{32}$/);
    expect(res.expires_in_ms).toBe(30_000);
  });

  it("viewport_query request with a filter present (skp/0.1)", () => {
    const req = loadFixture<ViewportQueryRequest>("v0-viewport_query-request-with-filter");
    assertExactKeys(
      req,
      ["skp", "dataset", "bbox", "bbox_crs", "limit", "filter"],
      "viewport_query request (with filter)"
    );
    expect(req.skp).toBe(SKP_VERSION);
    expect(req.bbox).toBeNull();
    expect(req.filter).not.toBeNull();
    assertExactKeys(req.filter, ["predicate", "dialect"], "viewport_query request .filter");
    expect(req.filter!.predicate).toBe("zone = 3 AND area > 100");
    expect(req.filter!.dialect).toBe(FILTER_DIALECT_DUCKDB_EXPR_0);
  });

  it("cancel request/response", () => {
    const req = loadFixture<CancelRequest>("v0-cancel-request");
    assertExactKeys(req, ["skp", "handle"], "cancel request");
    expect(req.handle).toMatch(/^sh_[0-9a-f]{32}$/);
    const res = loadFixture<CancelResponse>("v0-cancel-response");
    assertExactKeys(res, ["state"], "cancel response");
    expect(res.state).toBe("requested");
  });

  it("close_dataset request/response", () => {
    const req = loadFixture<CloseDatasetRequest>("v0-close_dataset-request");
    assertExactKeys(req, ["skp", "dataset"], "close_dataset request");
    expect(req.dataset).toMatch(/^ds_[0-9a-f]{32}$/);
    const res = loadFixture<CloseDatasetResponse>("v0-close_dataset-response");
    assertExactKeys(res, ["cancelled_streams"], "close_dataset response");
    expect(res.cancelled_streams).toBe(1);
  });

  it("a typed engine refusal crosses with its code, verbatim message, and named fields", () => {
    const err = loadFixture<SkpError>("v0-error-example");
    // `fields` is deliberately excluded from the key-set check above this line -- it is a
    // `Record<string, string>`, an open map whose keys vary per error code, not a fixed shape.
    assertExactKeys(err, ["code", "message", "fields"], "error example");
    expect(err.code).toBe("engine.crs_undeclared");
    expect(err.message).toContain("OGC:CRS84");
    expect(err.fields.detail).toBeDefined();
  });

  it("an identity_unusable refusal carries candidate_columns, schema order, comma-joined (skp/0.2)", () => {
    const err = loadFixture<SkpError>("v0-error-identity_unusable-with-candidates");
    assertExactKeys(err, ["code", "message", "fields"], "identity_unusable error example");
    expect(err.code).toBe("engine.identity_unusable");
    // `SkpError.fields` is `Record<string, string>` -- no list shape on the wire
    // (`kernel/src/skp.rs::error_of`), so the candidate list is comma-joined.
    expect(err.fields.candidate_columns).toBe("parcel_key,tax_lot_number");
  });

  it("every request fixture carries the current SKP_VERSION this client also sends", () => {
    for (const name of [
      "v0-open_dataset-request",
      "v0-open_dataset-request-with-crs_assertion-and-identity",
      "v0-describe-request",
      "v0-viewport_query-request",
      "v0-viewport_query-request-with-filter",
      "v0-cancel-request",
      "v0-close_dataset-request",
    ]) {
      const req = loadFixture<{ skp: string }>(name);
      expect(req.skp).toBe(SKP_VERSION);
    }
  });
});
