import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { decodeHexF64 } from "../codec";
import type {
  CancelRequest,
  CancelResponse,
  CloseDatasetRequest,
  CloseDatasetResponse,
  DescribeRequest,
  DescribeResponse,
  OpenDatasetRequest,
  OpenDatasetResponse,
  SkpError,
  ViewportQueryRequest,
  ViewportQueryResponse,
} from "../types";
import { SKP_VERSION } from "../types";

/**
 * One canonical request/response per command, read by **both** the Rust host
 * (`protocol/skp/tests/fixtures.rs`) and this client, generated by neither -- the same discipline
 * `renderer/tests/data/manifest-key-sets.json` already establishes for ADR-017: a reader and a
 * writer with separate hand-maintained tables can each stay green while disagreeing with each
 * other about the wire shape. This file is where they agree.
 */
const FIXTURE_DIR = path.resolve(__dirname, "../../../../../protocol/skp/tests/data");

function loadFixture<T>(name: string): T {
  const file = path.join(FIXTURE_DIR, `${name}.json`);
  return JSON.parse(fs.readFileSync(file, "utf-8")) as T;
}

describe("SKP v0 shared fixtures", () => {
  it("open_dataset request/response", () => {
    const req = loadFixture<OpenDatasetRequest>("v0-open_dataset-request");
    expect(req.skp).toBe(SKP_VERSION);
    expect(typeof req.path).toBe("string");
    expect(typeof req.cancel_key).toBe("string");

    const res = loadFixture<OpenDatasetResponse>("v0-open_dataset-response");
    expect(res.dataset).toMatch(/^ds_[0-9a-f]{32}$/);
  });

  it("describe request/response, including the two brief corrections (extent, row_count)", () => {
    const req = loadFixture<DescribeRequest>("v0-describe-request");
    expect(req.dataset).toMatch(/^ds_[0-9a-f]{32}$/);

    const res = loadFixture<DescribeResponse>("v0-describe-response");
    expect(res.crs.identifier).toBe("EPSG:2056");
    expect(res.crs.source).toBe("file");
    expect(res.geometry.frame).toBe("authoritative-project-crs");
    // C1: no bounds() accessor exists on the engine -- extent is honestly not established at open.
    expect(res.extent.basis).toBe("not-established-at-open");
    expect(res.extent.value).toBeNull();
    // C2: row_count carries its basis, never a bare integer.
    expect(res.row_count.basis).toBe("identity-uniqueness-scan-full-file");
    expect(res.row_count.value).toBe("100000");
    expect(res.identity.js_exact).toBe(true);
  });

  it("viewport_query request/response, with bbox edges as hex, never JSON numbers", () => {
    const req = loadFixture<ViewportQueryRequest>("v0-viewport_query-request");
    expect(req.bbox).not.toBeNull();
    expect(req.bbox!.xmin).toBe("0000000000000000");
    expect(decodeHexF64(req.bbox!.xmin)).toBe(0);
    expect(decodeHexF64(req.bbox!.xmax)).toBe(1);
    expect(decodeHexF64(req.bbox!.ymax)).toBe(2);
    expect(req.bbox_crs).toBeNull(); // declares "the dataset's own CRS" (SKP-V0.md §1)
    expect(req.limit).toBe("5000");

    const res = loadFixture<ViewportQueryResponse>("v0-viewport_query-response");
    expect(res.stream).toMatch(/^sh_[0-9a-f]{32}$/);
    expect(res.expires_in_ms).toBe(30_000);
  });

  it("cancel request/response", () => {
    const req = loadFixture<CancelRequest>("v0-cancel-request");
    expect(req.handle).toMatch(/^sh_[0-9a-f]{32}$/);
    const res = loadFixture<CancelResponse>("v0-cancel-response");
    expect(res.state).toBe("requested");
  });

  it("close_dataset request/response", () => {
    const req = loadFixture<CloseDatasetRequest>("v0-close_dataset-request");
    expect(req.dataset).toMatch(/^ds_[0-9a-f]{32}$/);
    const res = loadFixture<CloseDatasetResponse>("v0-close_dataset-response");
    expect(res.cancelled_streams).toBe(1);
  });

  it("a typed engine refusal crosses with its code, verbatim message, and named fields", () => {
    const err = loadFixture<SkpError>("v0-error-example");
    expect(err.code).toBe("engine.crs_undeclared");
    expect(err.message).toContain("OGC:CRS84");
    expect(err.fields.detail).toBeDefined();
  });

  it("every request fixture carries the current SKP_VERSION this client also sends", () => {
    for (const name of [
      "v0-open_dataset-request",
      "v0-describe-request",
      "v0-viewport_query-request",
      "v0-cancel-request",
      "v0-close_dataset-request",
    ]) {
      const req = loadFixture<{ skp: string }>(name);
      expect(req.skp).toBe(SKP_VERSION);
    }
  });
});
