#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

// Viewport-residency cut P3r (RESIDENCY-PREREGISTRATION.md §12 Amendment 16, the "measure build").
// `npm run build:measure`'s own build-time config overlay, generated fresh on every invocation --
// same pattern `e2e/lib.mjs`'s `writeConfigOverlay` already establishes for `tauri dev --config
// <path>` (copies `app.windows[0]` from the real config rather than inventing a window object, so
// title/width/height stay whatever the base config says instead of drifting out of sync with it),
// applied here to `tauri build --config <path>` instead.
//
// Two overrides, both required together:
//   1. `app.windows[0].create = false` -- prevents Tauri's own internal `setup()` (which runs BEFORE
//      the user `.setup(...)` closure, `tauri-2.11.5/src/app.rs`, verified reading it directly) from
//      auto-creating the declarative window. `lib.rs`'s own `#[cfg(feature = "measure-build")]` block
//      builds that SAME window itself instead, adding the CDP remote-debugging port
//      `additionalBrowserArgs` cannot otherwise reach at runtime (Tauri's config is embedded into the
//      binary at compile time via `tauri::generate_context!()`; there is no way to set
//      `additionalBrowserArgs` from an env var read at runtime without building the window in Rust).
//   2. `build.frontendDist = "../dist-measure"` and `build.beforeBuildCommand =
//      "npm run build:frontend:measure"` -- the measure build's own frontend output lives in
//      `dist-measure/`, never `dist/`, so `npm run check:dist-clean` (which only ever greps `dist/`,
//      `e2e/checkDistClean.mjs`'s own `DIST_DIR` constant) never sees it and a NORMAL `npm run
//      build`/`npm run verify` afterward still produces and checks a clean `dist/` untouched by this
//      overlay.
//
// Output path (`e2e/out/tauri.measure.conf.json`) lives inside `e2e/out/`, this workspace's own
// existing gitignored scratch directory (`.gitignore`'s `e2e/out/` line, `e2e/lib.mjs`'s own overlay
// uses the same directory) -- never committed, regenerated by every `npm run build:measure` call.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SHELL_DIR = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT_DIR = join(SHELL_DIR, "e2e", "out");

export function writeMeasureConfigOverlay() {
  const baseConfigPath = join(SHELL_DIR, "src-tauri", "tauri.conf.json");
  const baseConfig = JSON.parse(readFileSync(baseConfigPath, "utf8"));
  const baseWindow = baseConfig.app?.windows?.[0];
  if (!baseWindow) {
    throw new Error(`writeMeasureConfigOverlay: ${baseConfigPath} has no app.windows[0] to overlay onto`);
  }
  const overlayWindow = { ...baseWindow, create: false };
  const overlay = {
    build: {
      frontendDist: "../dist-measure",
      beforeBuildCommand: "npm run build:frontend:measure",
    },
    app: { windows: [overlayWindow] },
  };

  mkdirSync(OUT_DIR, { recursive: true });
  const overlayPath = join(OUT_DIR, "tauri.measure.conf.json");
  writeFileSync(overlayPath, JSON.stringify(overlay, null, 2));
  return overlayPath;
}

// `npm run build:measure`'s first step -- always runs when this file is invoked via `node
// e2e/writeMeasureConfigOverlay.mjs` (package.json's own script), unconditionally, matching
// `residency-harness.mjs`'s own top-level `await main()` convention rather than a fragile
// "run only as a script" entry-point check.
const path = writeMeasureConfigOverlay();
console.log(`writeMeasureConfigOverlay: wrote ${path}`);
