// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

// RELEASE-0.1 Amendment 3, item A: `tauri.conf.json` is JSON, not TypeScript, so `tsc` proves
// nothing about it -- this is the "unit-test the config" this piece's brief asks for. Read via
// `node:fs`, not a TS import: the file lives under `src-tauri/`, outside this package's own
// `tsconfig.json` `include` (`src`), and a plain read keeps this test correct regardless of how
// TypeScript's module graph is configured.
//
// **Exact strings, not `.includes()`/`.toContain()` (release-cut fix batch, SHOULD-FIX S3).** A
// resource glob one directory level off still CONTAINS "renderer/bundle-viewer/dist" as a
// substring while matching NO files at build time -- a loose check would pass on a config that
// silently ships an empty resource. This test instead asserts the exact source-glob string AND
// resolves it (with `resource_dir/*` -> `resource_dir`) against this checkout's own disk, so a
// wrong depth fails here even before a `tauri build` would fail on it.
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const here = dirname(fileURLToPath(import.meta.url));
const srcTauriDir = join(here, "..", "..", "src-tauri");
const configPath = join(srcTauriDir, "tauri.conf.json");
const config = JSON.parse(readFileSync(configPath, "utf8")) as {
  bundle: {
    targets: unknown;
    windows?: { nsis?: { installMode?: unknown } };
    resources?: unknown;
  };
};

const VIEWER_DIST_GLOB = "../../../renderer/bundle-viewer/dist/*";
const NOTICE_SOURCE = "../src/generated/NOTICE.txt";

describe("frontends/shell/src-tauri/tauri.conf.json (RELEASE-0.1 item A)", () => {
  it("bundles exactly nsis -- the human's ruling: NSIS only, no MSI", () => {
    expect(config.bundle.targets).toEqual(["nsis"]);
  });

  it("installs per-user, no elevation (tauri-utils 2.9.3 NSISInstallerMode::CurrentUser -- \"doesn't require Administrator access\")", () => {
    expect(config.bundle.windows?.nsis?.installMode).toBe("currentUser");
  });

  it("ships the bundle viewer's dist/ as a named resource directory, at exactly the resolvable glob", () => {
    const resources = config.bundle.resources as Record<string, string>;
    expect(resources[VIEWER_DIST_GLOB], `expected the exact key "${VIEWER_DIST_GLOB}"`).toBe("bundle-viewer/");
    // The glob's own fixed prefix (strip the trailing `/*`), resolved relative to src-tauri --
    // the same base Tauri's own bundler resolves it against. If this directory does not exist,
    // the glob matches nothing and `bundle.resources` silently ships an empty `bundle-viewer/`.
    const resolvedDir = join(srcTauriDir, VIEWER_DIST_GLOB.replace(/\/\*$/, ""));
    expect(existsSync(resolvedDir), `${resolvedDir} does not exist -- the resource glob would match nothing`).toBe(
      true
    );
  });

  it("ships the generated NOTICE.txt beside the executable, at exactly the resolvable source path", () => {
    const resources = config.bundle.resources as Record<string, string>;
    expect(resources[NOTICE_SOURCE], `expected the exact key "${NOTICE_SOURCE}"`).toBe("NOTICE.txt");
    // Existence is NOT asserted here (unlike the viewer dir above): this file is generated by the
    // `pretypecheck`/`prebuild` step this very test run's own `vitest` invocation triggers, so it
    // may not exist yet at the moment this file is first evaluated depending on script ordering --
    // asserting a path this test's own harness is responsible for producing would be circular.
    const resolvedPath = join(srcTauriDir, NOTICE_SOURCE);
    expect(resolvedPath.endsWith(join("frontends", "shell", "src", "generated", "NOTICE.txt"))).toBe(true);
  });
});
