// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

//! The anti-"renders-live-refuses-at-publish" evidence (NEXT-CUT.md style-panel cut P6).
//!
//! `frontends/shell` is style v0's second consumer (ADR-022; `CUT-STATE.md`'s own P1 section) --
//! it renders a style live, but never canonicalizes, hashes, or publishes one (binding note 3/8).
//! The hazard this test exists to catch is narrower than `style_agreement.rs`'s own cross-language
//! resolution contract: a document the shell is happy to RENDER (its own `document.ts::
//! toStyleDocument` producing something `renderer/style-ts`'s resolver accepts) that
//! `spatial_renderer::style::parse` -- the SAME grammar `publish-bundle --style` compiles against --
//! would silently REFUSE at publish time, discovered only after an operator has already been
//! shown a working live style with nothing telling them the round trip would fail.
//!
//! `tests/data/shell-emitted-styles.json` is a **checked-in fixture, not generated by this test**:
//! two real documents produced by the shell's own `document.ts::toStyleDocument` (a one-time,
//! throwaway vitest generator run once, its output hand-verified then checked in here, then
//! deleted -- the same disposal convention `CUT-STATE.md` names for this repo's Rust
//! `pilot_p3_*.rs`-style throwaway probes). `default_document` is `DEFAULT_STYLE_STATE`;
//! `changed_document` is the exact literal combination `e2e/style.mjs`'s `OUTLINE'` step actually
//! drove through the real panel DOM and rendered (E2E-verified) -- so this Rust-side acceptance
//! check and that E2E-verified render are evidence about the identical bytes, not two disconnected
//! sets of numbers.
//!
//! **Genuinely verbatim bytes, not a re-serialization (reviewer gate, style-panel cut P7 fixes,
//! S3).** The fixture's two documents are JSON STRINGS holding the exact COMPACT
//! `JSON.stringify(doc)` text `document.ts::resolveDrawParameters` itself feeds to `Style.parse` on
//! the real live-render path -- read directly with `.as_str()` below and handed to `parse` UNCHANGED.
//! An earlier version of this fixture embedded the documents as nested JSON objects, which forced
//! this test to `serde_json::to_string` them back into text before calling `parse` -- a
//! re-serialization whose key order (`serde_json::Value`'s own `Map`, sorted unless the
//! `preserve_order` feature is on) was not provably the shell's own insertion order, so the old
//! comment's "verbatim bytes" claim was not actually being tested. This shape closes that gap
//! structurally: there is no serialization step between the fixture and `parse` for this test to
//! introduce a difference in.
//!
//! Both documents are literal-only (style v0's own live-editing ceiling, ADR-023: `viewport_query`
//! carries no attributes, so a shell-produced document can never declare a `match`) -- `compile`
//! below is therefore called against a **minimal stub schema**: an empty column list and an empty
//! published-column list. Read, not assumed: `compiled.rs::compile` only ever consults `schema`/
//! `published` when `document.match_column()` is `Some` (to validate a match column exists, is
//! typed correctly, and is published); a literal-only document's `match_column()` is always `None`,
//! so an empty schema is not a weaker case here -- it is the same input a shell-emitted document
//! would produce for ANY dataset schema, precisely because it never depends on one.

use spatial_renderer::compile;
use spatial_renderer::style::parse;

use arrow::datatypes::DataType;

const FIXTURE: &str = include_str!("data/shell-emitted-styles.json");

/// No columns, no published projection -- see this file's own top doc comment for why this is a
/// faithful stand-in for "any dataset schema at all," not a weakened one, for a literal-only style.
const EMPTY_SCHEMA: &[(String, DataType)] = &[];
const EMPTY_PUBLISHED: &[String] = &[];

fn hex(c: spatial_renderer::style::Rgb) -> String {
    c.to_hex()
}

#[test]
fn shell_emitted_documents_are_accepted_by_the_publish_side_grammar() {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture is JSON");

    for (label, key) in [("default_document", "default_document"), ("changed_document", "changed_document")] {
        // Read directly as a string and handed to `parse` UNCHANGED (S3) -- no
        // `serde_json::to_string` round trip in between, so this really is the shell's own bytes,
        // not a re-serialized approximation of them. `doc` (below, for the field-by-field
        // expected-value assertions in step 3) is a SEPARATE parse of that same string, purely for
        // this test's own convenience reading fields back out -- it is never what gets handed to
        // `parse`/`compile`.
        let src = v[key].as_str().unwrap_or_else(|| panic!("fixture's `{key}` is missing or not a string"));
        let doc: serde_json::Value = serde_json::from_str(src).expect("fixture string is valid JSON");

        // 1. `spatial_renderer::style::parse` -- the same grammar `publish-bundle --style` compiles
        // against -- accepts the document the shell actually emitted, verbatim bytes (see this
        // file's own top doc comment, S3, for why this is now actually true rather than merely
        // claimed).
        let parsed = parse(src);
        assert!(
            parsed.is_ok(),
            "spatial_renderer::style::parse refused the shell-emitted `{label}`: {:?}\nsrc: {src}",
            parsed.err()
        );

        // 2. `compile` succeeds against the minimal stub schema (this file's own top doc comment)
        // -- the full path `publish-bundle --style` actually runs, not parse alone.
        let compiled = compile(src, EMPTY_SCHEMA, EMPTY_PUBLISHED);
        assert!(
            compiled.is_ok(),
            "spatial_renderer::compile refused the shell-emitted `{label}` against an empty schema: {:?}\nsrc: {src}",
            compiled.err()
        );
        let compiled = compiled.unwrap();

        // 3. Not vacuous: resolving the literal-only document (key `None`, exactly what
        // `document.ts::resolveDrawParameters` itself calls -- "every branch resolve could take
        // returns the identical draw parameters" per that module's own doc comment) reproduces the
        // SAME literal values the fixture's own document declares, proving `compile`/`resolve`
        // actually read this document's fields rather than merely accepting well-formed JSON.
        let expected_fill_color = doc["layer"]["fill_color"]["literal"].as_str().unwrap();
        let expected_fill_opacity = doc["layer"]["fill_opacity"]["literal"].as_f64().unwrap();
        let expected_outline_color = doc["layer"]["outline_color"]["literal"].as_str().unwrap();
        let expected_outline_width = doc["layer"]["outline_width"]["literal"].as_f64().unwrap();

        let resolved = compiled.resolve(None);
        assert_eq!(hex(resolved.fill_color), expected_fill_color, "fill_color at {label}");
        assert_eq!(resolved.fill_opacity, expected_fill_opacity, "fill_opacity at {label}");
        assert_eq!(hex(resolved.outline_color), expected_outline_color, "outline_color at {label}");
        assert_eq!(resolved.outline_width, expected_outline_width, "outline_width at {label}");
    }
}
