// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

//! The publish operation end to end, against real files.
//!
//! Everything the bundle format *promises* is asserted here against an emitted bundle rather than
//! against the code's intentions: determinism is two publishes compared byte for byte, redaction is
//! a scan over every byte of every emitted file, and "no partial bundle" is a directory listing
//! after a cancel.

use arrow::array::Array as _;
use std::path::{Path, PathBuf};

use spatial_engine::fixture::{
    write_geoparquet, AttributeMode, CrsMode, FixtureSpec, IdentityMode, LicenseMode,
};
use spatial_engine::{CancelToken, Dataset, ViewportQuery};
use spatial_kernel::bundle::{self, redaction};
use spatial_kernel::publish::{
    publish, CorrespondingSource, CorrespondingSourceKind, OperatorLicense, PublishError,
    PublishPhase, PublishProgress, PublishRequest, ViewerAsset, ViewerAssets, ViewerLicenseInput,
};

const STYLE: &str = r##"{
  "style_version": 1,
  "layer": {
    "geometry": "polygon",
    "fill_color": {"match": {
      "column": "zone",
      "cases": [{"when": "residential", "then": "#aa3333"},
                {"when": "industrial",  "then": "#333388"}],
      "on_null": "#888888",
      "on_unmatched": "#cccccc"}},
    "fill_opacity": {"literal": 0.8},
    "outline_color": {"literal": "#202020"},
    "outline_width": {"literal": 1.0}
  }
}"##;

fn workspace(name: &str) -> PathBuf {
    let d = std::env::temp_dir().join("spatial-kernel-publish-tests").join(name);
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn fixture(dir: &Path, features: usize) -> PathBuf {
    let path = dir.join("parcels.parquet");
    write_geoparquet(
        &path,
        &FixtureSpec {
            features,
            attributes: AttributeMode::CategoricalZone,
            crs_mode: CrsMode::DeclaredLv95,
            identity: IdentityMode::NativeUnique,
            ..Default::default()
        },
    )
    .unwrap();
    path
}

fn pinned(path: &Path) -> Dataset {
    let ds = Dataset::open(path).unwrap();
    ds.pin_content(&CancelToken::new()).unwrap();
    ds
}

fn viewer() -> ViewerAssets {
    // Synthetic, deliberately: a Rust test must not need Node to run. The acceptance run points at
    // the real built viewer instead.
    ViewerAssets::new(vec![
        ViewerAsset { path: "index.html".into(), bytes: b"<!doctype html><title>t</title>".to_vec() },
        ViewerAsset { path: "app.js".into(), bytes: b"export const ok = 1;\n".to_vec() },
        // The notice `viewer_license.notice_path` points at. Synthetic like the rest — the *format*
        // requires the declaration to name a hash-listed asset and deliberately cannot check what
        // is inside it (ADR-017 Corrigendum 3), so a stub is the honest fixture. The real notice
        // set is generated by `renderer/bundle-viewer/build.mjs` and reaches the acceptance run.
        ViewerAsset { path: "NOTICE.txt".into(), bytes: b"stub notice\n".to_vec() },
    ])
    .unwrap()
}

/// The `viewer_license` every request needs (ADR-009 item 7; ADR-017 Corrigendum 3).
///
/// `notice_path` is **viewer-relative** here, as `ViewerAsset::path` is; the publisher emits
/// `viewer/NOTICE.txt`. Tests that care about that translation assert it explicitly.
fn viewer_license() -> ViewerLicenseInput {
    ViewerLicenseInput {
        program: "Spatial IDE bundle viewer".into(),
        copyright: "Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors".into(),
        license: "AGPL-3.0-or-later".into(),
        notice_path: "NOTICE.txt".into(),
        corresponding_source: CorrespondingSource {
            kind: CorrespondingSourceKind::Url,
            at: "https://example.invalid/spatial-ide".into(),
        },
    }
}

fn request<'a>(
    ds: &'a Dataset,
    viewer: &'a ViewerAssets,
    destination: PathBuf,
) -> PublishRequest<'a> {
    PublishRequest {
        dataset: ds,
        dataset_name: "parcels",
        query: ViewportQuery::all(),
        attributes: vec!["zone".into()],
        style_source: STYLE,
        viewer,
        viewer_license: viewer_license(),
        license: None,
        destination,
        // Fixed instants: the operation is a pure function of its inputs, and these reach only the
        // sidecar, which no hash covers.
        started_at: "2026-08-06T09:00:00Z".into(),
        // A fixed clock: the sidecar is excluded from every hash, and a test that let a real one in
        // would be asserting determinism against a value designed to differ.
        finished_at: &FIXED_FINISH,
    }
}

/// The clock the tests hand to `publish`. Named so a test that wants a *different* instant can say
/// so, which `the_sidecar_is_what_differs_between_two_publishes_and_it_is_excluded_by_design` does.
fn fixed_finish() -> String {
    "2026-08-06T09:00:01Z".to_string()
}
static FIXED_FINISH: fn() -> String = fixed_finish;

fn later_finish() -> String {
    "2027-01-01T00:00:05Z".to_string()
}
static LATER_FINISH: fn() -> String = later_finish;

fn read(bundle: &Path, rel: &str) -> Vec<u8> {
    std::fs::read(bundle.join(rel)).unwrap_or_else(|e| panic!("read {rel}: {e}"))
}

#[test]
fn a_published_bundle_has_the_declared_layout_and_lists_every_asset_it_contains() {
    let d = workspace("layout");
    let ds = pinned(&fixture(&d, 3_000));
    let v = viewer();
    let dest = d.join("bundle");
    let out = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();

    assert!(dest.join(bundle::MANIFEST_PATH).is_file());
    assert!(dest.join(bundle::STYLE_PATH).is_file());
    assert!(dest.join(bundle::BUILD_INFO_PATH).is_file());
    assert!(dest.join("viewer/index.html").is_file());
    assert!(dest.join(bundle::partition_path(0)).is_file());
    assert_eq!(out.rows, 3_000);
    assert!(out.partitions >= 1);
    assert_eq!(out.reproducibility_grade, "Snapshot");

    // Every listed asset exists, is the listed length, and hashes to the listed hash. This is the
    // property the viewer's verification depends on, checked here from the writing side.
    let manifest: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();
    let listed: Vec<&serde_json::Value> = manifest["data"]["partitions"]
        .as_array()
        .unwrap()
        .iter()
        .chain(manifest["viewer"].as_array().unwrap())
        .collect();
    assert!(listed.len() >= 3);
    for asset in listed {
        let rel = asset["path"].as_str().unwrap();
        let bytes = read(&dest, rel);
        assert_eq!(bytes.len() as u64, asset["bytes"].as_u64().unwrap(), "{rel} length");
        assert_eq!(
            spatial_renderer::sha256_hex(&bytes),
            asset["content_hash"].as_str().unwrap(),
            "{rel} hash"
        );
    }
    // The style is listed separately, under its own ResourceRef, and hashes too.
    assert_eq!(
        spatial_renderer::sha256_hex(&read(&dest, bundle::STYLE_PATH)),
        manifest["style"]["resource"]["content_hash"].as_str().unwrap()
    );

    // The sidecar is named but NOT hashed and NOT verified — and the manifest says so, so a reader
    // is not left to discover it.
    assert_eq!(manifest["sidecar"]["path"].as_str().unwrap(), bundle::BUILD_INFO_PATH);
    assert_eq!(manifest["sidecar"]["hashed"].as_bool().unwrap(), false);
    assert_eq!(manifest["sidecar"]["verified"].as_bool().unwrap(), false);
}

#[test]
fn publishing_twice_from_identical_inputs_gives_a_byte_identical_manifest() {
    // The acceptance criterion, and the reason the ordering, the fixed partition policy and the
    // canonical number grammar all exist.
    let d = workspace("determinism");
    let src = fixture(&d, 4_000);
    let v = viewer();

    let ds_a = pinned(&src);
    let a = publish(&request(&ds_a, &v, d.join("a")), &CancelToken::new(), None).unwrap();
    // A second *open* as well as a second publish: the manifest must not depend on process state
    // that happens to survive between the two.
    let ds_b = pinned(&src);
    let b = publish(&request(&ds_b, &v, d.join("b")), &CancelToken::new(), None).unwrap();

    let ma = read(&d.join("a"), bundle::MANIFEST_PATH);
    let mb = read(&d.join("b"), bundle::MANIFEST_PATH);
    assert_eq!(ma, mb, "two publishes produced different manifest bytes");
    assert_eq!(a.style_hash, b.style_hash);
    assert_eq!(a.operation_digest, b.operation_digest);
    assert_eq!(a.partitions, b.partitions);

    // …and every partition is byte-identical, which is the thing the manifest's hashes assert.
    for i in 0..a.partitions {
        let rel = bundle::partition_path(i);
        assert_eq!(read(&d.join("a"), &rel), read(&d.join("b"), &rel), "partition {i} differs");
    }
    // The style bytes too.
    assert_eq!(read(&d.join("a"), bundle::STYLE_PATH), read(&d.join("b"), bundle::STYLE_PATH));
}

/// **The operator-declared branch is inside the determinism guarantee, and `license.at` is why.**
///
/// ADR-017 §12 scopes byte-identity to "identical source bytes, style bytes, declared projection,
/// publish parameters and viewer asset bytes" — and §10 places `license.at` among the *parameters*,
/// because it describes the **request** (an operator declared terms at an instant) rather than the
/// **execution**. Both halves of that are asserted here, and both were unasserted before: the
/// shared `request()` helper sets `license: None`, so the determinism test above never reached this
/// branch at all.
///
/// It is not a hypothetical gap. `publish-bundle` passed its own build clock as `license.at`, so
/// every operator-declared publish produced a different manifest — the guarantee was false for the
/// whole branch and no test could see it. The binary now requires `--license-at`.
#[test]
fn two_operator_declared_publishes_agree_byte_for_byte_and_a_different_instant_is_a_different_publish()
{
    let d = workspace("operator-license-determinism");
    let src = fixture(&d, 800);
    let v = viewer();

    let declaration = |at: &str| OperatorLicense {
        license: "CC-BY-4.0".into(),
        attribution: Some("© Example Cadastre".into()),
        redistribution: bundle::Redistribution::Permitted,
        by: "operator".into(),
        at: at.into(),
    };

    let ds_a = pinned(&src);
    let mut a = request(&ds_a, &v, d.join("a"));
    a.license = Some(declaration("2026-08-06T09:00:00Z"));
    publish(&a, &CancelToken::new(), None).unwrap();

    // Same declaration, a second open, and a **later build** — the sidecar's instants differ.
    let ds_b = pinned(&src);
    let mut b = request(&ds_b, &v, d.join("b"));
    b.license = Some(declaration("2026-08-06T09:00:00Z"));
    b.started_at = "2027-01-01T00:00:00Z".into();
    b.finished_at = &LATER_FINISH;
    publish(&b, &CancelToken::new(), None).unwrap();

    assert_eq!(
        read(&d.join("a"), bundle::MANIFEST_PATH),
        read(&d.join("b"), bundle::MANIFEST_PATH),
        "build timing reached the manifest through the operator-declared license branch"
    );
    assert_ne!(
        read(&d.join("a"), bundle::BUILD_INFO_PATH),
        read(&d.join("b"), bundle::BUILD_INFO_PATH),
        "the two builds were not actually distinguishable, so the assertion above proves nothing"
    );

    // …and the other half: a **different declaration instant is a different request**, so it must
    // produce a different manifest. Without this, `license.at` could be silently dropped from the
    // manifest entirely and the assertion above would still pass.
    let ds_c = pinned(&src);
    let mut c = request(&ds_c, &v, d.join("c"));
    c.license = Some(declaration("2026-08-06T17:30:00Z"));
    publish(&c, &CancelToken::new(), None).unwrap();
    assert_ne!(
        read(&d.join("a"), bundle::MANIFEST_PATH),
        read(&d.join("c"), bundle::MANIFEST_PATH),
        "two different operator declarations produced one manifest; `license.at` is not carried"
    );

    let m: serde_json::Value =
        serde_json::from_slice(&read(&d.join("c"), bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(m["license"]["at"], "2026-08-06T17:30:00Z");
}

#[test]
fn the_sidecar_is_what_differs_between_two_publishes_and_it_is_excluded_by_design() {
    // If the wall-clock facts lived in the manifest, the assertion above would be false. This test
    // is the other half of that argument: the values really do differ, and they really are outside
    // every hash.
    let d = workspace("sidecar");
    let src = fixture(&d, 800);
    let v = viewer();

    let ds = pinned(&src);
    let mut req = request(&ds, &v, d.join("a"));
    publish(&req, &CancelToken::new(), None).unwrap();

    req.destination = d.join("b");
    req.started_at = "2027-01-01T00:00:00Z".into();
    req.finished_at = &LATER_FINISH;
    publish(&req, &CancelToken::new(), None).unwrap();

    assert_eq!(
        read(&d.join("a"), bundle::MANIFEST_PATH),
        read(&d.join("b"), bundle::MANIFEST_PATH),
        "a timestamp reached the manifest"
    );
    assert_ne!(
        read(&d.join("a"), bundle::BUILD_INFO_PATH),
        read(&d.join("b"), bundle::BUILD_INFO_PATH),
        "the sidecar did not record the instants it exists to record"
    );
}

#[test]
fn the_redaction_scan_passes_over_every_byte_of_an_emitted_bundle() {
    // docs/09, asserted over the artifact rather than over the intention. The scan reads every file
    // including the partitions and the sidecar.
    let d = workspace("redaction");
    let ds = pinned(&fixture(&d, 2_000));
    let v = viewer();
    let dest = d.join("bundle");
    publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();

    // **The operator's own declarations are supplied**, so a match inside one is attributed rather
    // than reported as a leak (ADR-017 Corrigendum 3). ADR-009 item 7 makes a copyright notice a
    // required manifest member, and on a single-maintainer machine the login name *is* the name in
    // that notice — the scan sees a username and cannot tell, from bytes, that the operator typed
    // it deliberately. Nothing is suppressed: `redaction.rs` re-classes only a match lying wholly
    // inside a declared occurrence, and its own unit tests pin both halves of that.
    let vl = viewer_license();
    let machine = redaction::MachineIdentifiers {
        declared: vec![vl.copyright.clone(), vl.corresponding_source.at.clone()],
        ..redaction::MachineIdentifiers::from_environment()
    };
    let findings = redaction::scan_directory(&dest, &machine).unwrap();
    // Undeclared findings are the ones that mean something went wrong. Declared ones are listed
    // separately below rather than dropped, so this test cannot pass by explaining everything away.
    let leaked: Vec<_> = findings
        .iter()
        .filter(|f| f.class != redaction::OPERATOR_DECLARED)
        .collect();
    assert!(leaked.is_empty(), "redaction findings in the emitted bundle: {leaked:#?}");

    // …and the attribution is doing real work rather than being dead configuration: on a machine
    // whose username appears in the declared copyright there **is** a re-classed finding, and this
    // asserts the mechanism is exercised when that is so. On a machine where it is not, there is
    // nothing to attribute and nothing to assert — stated rather than left as a flaky expectation.
    if vl.copyright.to_lowercase().contains(
        &machine.usernames.first().cloned().unwrap_or_else(|| "\u{0}".into()).to_lowercase(),
    ) {
        assert!(
            findings.iter().any(|f| f.class == redaction::OPERATOR_DECLARED),
            "the declared copyright contains this machine's username, so the scan should have \
             attributed a match rather than finding nothing: {findings:#?}"
        );
    }

    // The scan is only meaningful if it *can* fire — a grep that finds nothing because it looks for
    // nothing is not evidence. This is the same directory with one planted string.
    std::fs::write(dest.join("planted.txt"), b"opened C:\\dev\\secret.parquet").unwrap();
    let after = redaction::scan_directory(&dest, &machine).unwrap();
    assert!(
        after.iter().any(|f| f.class == "local-filesystem-path"),
        "the scan cannot detect what it claims to"
    );
}

#[test]
fn cancelling_mid_publish_leaves_no_bundle_and_no_staging_directory() {
    let d = workspace("cancel");
    let ds = pinned(&fixture(&d, 30_000));
    let v = viewer();
    let dest = d.join("bundle");

    // Cancel once the first partitions are on disk, so the cancel lands *during* writing rather
    // than before it starts — the case "no partial output" is actually about.
    struct CancelAfter {
        cancel: CancelToken,
        after: usize,
    }
    impl PublishProgress for CancelAfter {
        fn phase(&self, _: PublishPhase) {}
        fn partition_written(&self, index: usize, _: usize, _: u64) {
            if index + 1 >= self.after {
                self.cancel.cancel();
            }
        }
    }

    let cancel = CancelToken::new();
    let obs = CancelAfter { cancel: cancel.clone(), after: 2 };
    let e = publish(&request(&ds, &v, dest.clone()), &cancel, Some(&obs)).unwrap_err();
    assert!(matches!(e, PublishError::Cancelled), "got {e}");

    assert!(!dest.exists(), "a bundle exists under the destination name after a cancel");
    let leftovers: Vec<String> = std::fs::read_dir(&d)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().to_string())
        .filter(|n| n.contains("staging"))
        .collect();
    assert!(leftovers.is_empty(), "staging directories left behind: {leftovers:?}");
}

#[test]
fn an_existing_destination_is_refused_rather_than_replaced() {
    // ADR-006 class 3: publishing is irreversible, so re-running a command never destroys an
    // already-published bundle. Declared, not discovered.
    let d = workspace("exists");
    let ds = pinned(&fixture(&d, 500));
    let v = viewer();
    let dest = d.join("bundle");
    publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();

    let before = read(&dest, bundle::MANIFEST_PATH);
    let e = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap_err();
    assert!(matches!(e, PublishError::DestinationExists { .. }), "got {e}");
    assert_eq!(read(&dest, bundle::MANIFEST_PATH), before, "the existing bundle was touched");
}

#[test]
fn an_unpinned_source_is_refused_before_anything_is_written() {
    let d = workspace("unpinned");
    let ds = Dataset::open(fixture(&d, 200)).unwrap(); // deliberately not pinned
    let v = viewer();
    let dest = d.join("bundle");
    let e = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap_err();
    assert!(matches!(e, PublishError::SourceNotPinned), "got {e}");
    assert!(!dest.exists());
}

#[test]
fn a_source_that_changed_since_the_pin_is_detected_and_refused() {
    let d = workspace("changed");
    let src = fixture(&d, 400);
    let ds = pinned(&src);

    // Rewrite the file with a different feature count: same path, different bytes.
    write_geoparquet(
        &src,
        &FixtureSpec {
            features: 401,
            attributes: AttributeMode::CategoricalZone,
            ..Default::default()
        },
    )
    .unwrap();

    let v = viewer();
    let dest = d.join("bundle");
    let e = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap_err();
    match e {
        PublishError::Engine(spatial_engine::EngineError::SourceChangedUnderPublish {
            detected_by,
            ..
        }) => assert!(detected_by.contains("content hash"), "detected by {detected_by}"),
        other => panic!("got {other}"),
    }
    assert!(!dest.exists());
}

#[test]
fn a_style_whose_match_column_is_not_published_is_refused_at_publish_not_at_view_time() {
    let d = workspace("style-mismatch");
    let ds = pinned(&fixture(&d, 300));
    let v = viewer();
    let mut req = request(&ds, &v, d.join("bundle"));
    req.attributes = vec![]; // `zone` exists in the dataset but is not published
    let e = publish(&req, &CancelToken::new(), None).unwrap_err();
    assert!(
        matches!(
            e,
            PublishError::Style(spatial_renderer::StyleError::MatchColumnNotPublished { .. })
        ),
        "got {e}"
    );
    assert!(!d.join("bundle").exists());
}

#[test]
fn the_manifest_carries_the_docs_11_resource_refs_the_grade_and_the_transform_fact() {
    let d = workspace("manifest-contents");
    let ds = pinned(&fixture(&d, 600));
    let v = viewer();
    let dest = d.join("bundle");
    publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();
    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();

    // Three ResourceRefs, each with all six docs/11 members named.
    for block in [&m["bundle"], &m["source"], &m["style"]["resource"]] {
        for member in [
            "logical_uri",
            "content_hash",
            "source_revision",
            "locators",
            "cache_status",
            "portability_policy",
        ] {
            assert!(!block[member].is_null(), "missing {member} in {block}");
        }
        // An unknown member is a named state carrying its basis, never a bare null.
        if block["source_revision"].is_object() {
            assert!(block["source_revision"]["state"].is_string());
            assert!(block["source_revision"]["basis"].is_string());
        }
    }

    // The decided publishing path, recorded as a fact.
    assert_eq!(m["crs"]["transform"].as_str().unwrap(), "none — rendered in source CRS");
    assert_eq!(m["crs"]["source"].as_str().unwrap(), "EPSG:2056");
    assert_eq!(m["crs"]["display"].as_str().unwrap(), "EPSG:2056");
    assert_eq!(m["crs"]["axis_normalization"].as_str().unwrap(), "none-performed");

    // ADR-016's envelope facts, plus the caveat that says what they do not establish.
    assert_eq!(m["identity"]["id_source"].as_str().unwrap(), "file:id");
    assert_eq!(m["identity"]["id_uniqueness"].as_str().unwrap(), "verified-at-open-full-file");
    assert!(m["identity"]["caveat"].as_str().unwrap().contains("Stability across reopen"));

    // ADR-005: the grade, its basis, and why not higher.
    assert_eq!(m["reproducibility"]["grade"].as_str().unwrap(), "Snapshot");
    assert!(!m["reproducibility"]["basis"].as_array().unwrap().is_empty());
    assert!(m["reproducibility"]["why_not_higher"].as_str().unwrap().contains("Exact"));

    // License, honestly absent — the fixture declares none and nothing is invented.
    assert_eq!(m["license"]["state"].as_str().unwrap(), "not-declared");

    // Bounds computed over published rows, not lifted from the file's covering bbox.
    assert_eq!(m["bounds"]["basis"].as_str().unwrap(), "computed-over-published-rows");

    // The reservations exist in v1 so filling them later is not a format change.
    assert!(m["derived_caches"].as_array().unwrap().is_empty());
    assert_eq!(m["query_surface"]["available"].as_bool().unwrap(), false);

    // The format is declared normatively enough for an independent writer.
    let f = &m["data"]["format"];
    assert_eq!(f["compression"].as_str().unwrap(), "none");
    assert_eq!(f["dictionaries"].as_str().unwrap(), "none");
    assert_eq!(f["framing"].as_str().unwrap(), "arrow-ipc-stream-per-partition");
    assert_eq!(f["partition_boundary_rule"].as_str().unwrap(), "cut-before-append");

    // The operation is carried as data beside its digest, so the digest can be recomputed.
    assert!(m["operation"]["digest"].as_str().unwrap().starts_with("sha256:"));
    assert_eq!(m["operation"]["ordering"].as_str().unwrap(), "identity-ascending");
    assert_eq!(m["operation"]["filter"]["kind"].as_str().unwrap(), "whole-file");
    // Named for what it is: no "SQL", no "intersection".
    let manifest_text = String::from_utf8(read(&dest, bundle::MANIFEST_PATH)).unwrap();
    assert!(!manifest_text.contains("read_parquet"), "generated SQL reached the manifest");
}

#[test]
fn a_filtered_publish_records_the_filter_and_bounds_the_rows_it_actually_wrote() {
    let d = workspace("filtered");
    let ds = pinned(&fixture(&d, 4_000));
    let v = viewer();
    let dest = d.join("bundle");

    let mut req = request(&ds, &v, dest.clone());
    // A quarter-extent-ish viewport in the fixture's own CRS.
    req.query = ViewportQuery::viewport(
        spatial_engine::Bbox {
            xmin: 2_600_000.0,
            ymin: 1_200_000.0,
            xmax: 2_601_000.0,
            ymax: 1_201_000.0,
        },
        "EPSG:2056",
    );
    let out = publish(&req, &CancelToken::new(), None).unwrap();
    assert!(out.rows > 0 && out.rows < 4_000, "the viewport selected {} of 4000", out.rows);

    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(
        m["operation"]["filter"]["kind"].as_str().unwrap(),
        "covering-bbox-intersects",
        "the filter must be named for what it is, not called `intersection`"
    );

    // Bounds describe the published rows. The file's own covering bbox spans the whole fixture, so
    // a bundle that lifted bounds from it would open on a mostly-empty map.
    let b = &m["bounds"];
    let (xmin, xmax) = (b["xmin"].as_f64().unwrap(), b["xmax"].as_f64().unwrap());
    assert!(xmin >= 2_600_000.0 - 100.0, "xmin {xmin} looks like the whole file's");
    assert!(xmax < 2_610_000.0, "xmax {xmax} looks like the whole file's");
}

#[test]
fn an_operator_may_declare_a_license_for_a_source_that_declares_none() {
    let d = workspace("operator-license");
    let ds = pinned(&fixture(&d, 300));
    let v = viewer();
    let dest = d.join("bundle");
    let mut req = request(&ds, &v, dest.clone());
    req.license = Some(OperatorLicense {
        license: "CC-BY-4.0".into(),
        attribution: Some("© Example Cadastre".into()),
        redistribution: bundle::Redistribution::Permitted,
        by: "operator".into(),
        at: "2026-08-06T09:00:00Z".into(),
    });
    publish(&req, &CancelToken::new(), None).unwrap();

    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();
    // A claim carries its claimant — the crs_source / id_source shape, applied to license.
    assert_eq!(m["license"]["state"].as_str().unwrap(), "declared-by-operator");
    assert_eq!(m["license"]["license"].as_str().unwrap(), "CC-BY-4.0");
    assert_eq!(m["license"]["by"].as_str().unwrap(), "operator");
    assert_eq!(m["license"]["redistribution"].as_str().unwrap(), "permitted");
}

#[test]
fn a_viewer_asset_path_that_escapes_the_bundle_is_refused() {
    let d = workspace("asset-escape");
    let ds = pinned(&fixture(&d, 100));
    let bad = ViewerAssets::new(vec![ViewerAsset {
        path: "../escape.js".into(),
        bytes: b"x".to_vec(),
    }]);
    assert!(matches!(bad, Err(PublishError::ViewerAssetPathRejected { .. })));
    // And a valid set still publishes, so the check is not simply refusing everything.
    let v = viewer();
    publish(&request(&ds, &v, d.join("ok")), &CancelToken::new(), None).unwrap();
}

#[test]
fn every_partition_carries_the_adr_010_rule_1_envelope_and_the_declared_projection() {
    let d = workspace("envelope");
    let ds = pinned(&fixture(&d, 5_000));
    let v = viewer();
    let dest = d.join("bundle");
    let out = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();
    assert!(out.partitions > 1, "expected several partitions, got {}", out.partitions);

    // Every one, not just the first: the envelope repeats per partition precisely so a reader that
    // starts anywhere is still told what space the coordinates are in.
    for i in 0..out.partitions {
        let bytes = read(&dest, &bundle::partition_path(i));
        let mut rdr =
            arrow::ipc::reader::StreamReader::try_new(std::io::Cursor::new(&bytes), None).unwrap();
        let batch = rdr.next().unwrap().unwrap();
        let md = batch.schema().metadata().clone();
        assert_eq!(md.get("frame").unwrap(), spatial_engine::FRAME_AUTHORITATIVE, "partition {i}");
        assert_eq!(md.get("crs").unwrap(), "EPSG:2056");
        assert_eq!(md.get("axis_order").unwrap(), "easting,northing");
        assert_eq!(md.get("attribute_columns").unwrap(), r#"["zone"]"#);
        assert_eq!(batch.schema().field(0).name(), "id");
        assert_eq!(batch.schema().field(2).name(), "zone");
        assert!(batch.schema().field(2).is_nullable(), "a published attribute must carry NULLs");
        // And the stream really is one self-contained IPC stream per partition: one batch, then EOS.
        assert!(rdr.next().is_none(), "partition {i} carries more than one record batch");
    }
}

#[test]
fn ids_ascend_across_partitions_and_the_null_branch_reaches_the_bundle() {
    let d = workspace("ordering-and-nulls");
    let ds = pinned(&fixture(&d, 6_000));
    let v = viewer();
    let dest = d.join("bundle");
    let out = publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();

    let mut previous: Option<u64> = None;
    let mut saw_null = false;
    let mut saw_value = false;
    for i in 0..out.partitions {
        let bytes = read(&dest, &bundle::partition_path(i));
        let mut rdr =
            arrow::ipc::reader::StreamReader::try_new(std::io::Cursor::new(&bytes), None).unwrap();
        let batch = rdr.next().unwrap().unwrap();
        let ids = batch
            .column(0)
            .as_any()
            .downcast_ref::<arrow::array::UInt64Array>()
            .unwrap();
        for id in ids.values() {
            if let Some(p) = previous {
                assert!(*id > p, "ids are not ascending across partition {i}");
            }
            previous = Some(*id);
        }
        let zone = batch
            .column(2)
            .as_any()
            .downcast_ref::<arrow::array::StringArray>()
            .unwrap();
        for r in 0..zone.len() {
            if zone.is_null(r) {
                saw_null = true;
            } else {
                saw_value = true;
            }
        }
    }
    assert_eq!(previous, Some(5_999));
    // Both branches the style must declare actually travel, so `on_null` is exercised by a real
    // bundle rather than only by a unit test.
    assert!(saw_null, "no NULL zone reached the bundle");
    assert!(saw_value, "no non-NULL zone reached the bundle");
}

/// The **emitted** manifest's key sets, checked against the shared artifact — not against a table
/// in this file.
///
/// **The shared artifact is the point.** Before it existed, the writer's expected sets lived here
/// and the reader's lived in `renderer/bundle-viewer/src/manifest.ts`, each with a test over its
/// own table. Passing both proved less than it looked: editing the reader and its own test kept the
/// JS suite green while every real bundle became unreadable, and editing the writer and this table
/// kept Rust green while the reader still refused. Two hand-maintained tables guarantee only that
/// neither side moves without *its own* test failing, which is not agreement.
///
/// So both sides now read `renderer/tests/data/manifest-key-sets.json`, and **neither generates it
/// from its own output** — the discipline `renderer/tests/data/style-agreement.json` already
/// applies to style resolution. A writer that drifts fails here; a reader that drifts fails in
/// `scripts/manifest.test.mjs`; a change made to both without touching the artifact fails in both.
#[test]
fn the_emitted_manifest_has_exactly_the_key_sets_adr_017_declares() {
    const SHARED: &str = include_str!("../../renderer/tests/data/manifest-key-sets.json");
    let shared: serde_json::Value = serde_json::from_str(SHARED).expect("shared key sets are JSON");
    let want = |name: &str| -> Vec<String> {
        let mut v: Vec<String> = shared["key_sets"][name]
            .as_array()
            .unwrap_or_else(|| panic!("the shared artifact has no key set named `{name}`"))
            .iter()
            .map(|k| k.as_str().unwrap().to_string())
            .collect();
        v.sort();
        v
    };
    let got = |node: &serde_json::Value, at: &str| -> Vec<String> {
        let mut v: Vec<String> = node
            .as_object()
            .unwrap_or_else(|| panic!("{at} is not an object"))
            .keys()
            .cloned()
            .collect();
        v.sort();
        v
    };

    let d = workspace("manifest-key-sets");
    let ds = pinned(&fixture(&d, 400));
    let v = viewer();
    let dest = d.join("bundle");

    // An **operator-declared license** and a **bbox filter**, so the two shapes that appear only
    // under those options are covered here rather than only in the default case. `license.at` is
    // the declaration instant — a semantic input inside the determinism surface, not build timing.
    let mut req = request(&ds, &v, dest.clone());
    req.query = ViewportQuery::viewport(
        spatial_engine::Bbox {
            xmin: 2_600_000.0,
            ymin: 1_200_000.0,
            xmax: 2_612_000.0,
            ymax: 1_212_000.0,
        },
        "EPSG:2056",
    );
    req.license = Some(OperatorLicense {
        license: "CC-BY-4.0".into(),
        attribution: Some("(c) Example Cadastre".into()),
        redistribution: bundle::Redistribution::Permitted,
        by: "operator".into(),
        at: "2026-08-06T09:00:00Z".into(),
    });
    publish(&req, &CancelToken::new(), None).unwrap();
    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();

    // Objects addressed by path.
    for (path, set) in [
        ("$", "$"),
        ("bundle", "resource_ref"),
        ("source", "resource_ref"),
        ("style", "$.style"),
        ("style/resource", "resource_ref"),
        ("software", "$.software"),
        ("operation", "$.operation"),
        ("operation/format", "format"),
        ("crs", "$.crs"),
        ("identity", "$.identity"),
        ("bounds", "$.bounds"),
        ("data", "$.data"),
        ("data/format", "format"),
        ("viewer_license", "viewer_license"),
        ("viewer_license/corresponding_source", "viewer_license_corresponding_source"),
        ("license", "license_declared_by_operator"),
        ("reproducibility", "$.reproducibility"),
        ("query_surface", "$.query_surface"),
        ("sidecar", "$.sidecar"),
    ] {
        let node = if path == "$" {
            &m
        } else {
            path.split('/').fold(&m, |n, step| {
                n.get(step).unwrap_or_else(|| panic!("{path} is missing from the manifest"))
            })
        };
        assert_eq!(got(node, path), want(set), "{path} does not match the shared key set `{set}`");
    }

    // Repeating shapes, one element each — one code path emits them all.
    for (path, set) in [
        ("data/partitions", "partition"),
        ("viewer", "viewer_asset"),
        ("schema", "column"),
        ("operation/projection", "column"),
        ("bundle/locators", "locator"),
        ("source/locators", "locator"),
        ("style/resource/locators", "locator"),
    ] {
        let arr = path
            .split('/')
            .fold(&m, |n, step| &n[step])
            .as_array()
            .unwrap_or_else(|| panic!("{path} is not an array"));
        let first =
            arr.first().unwrap_or_else(|| panic!("{path} is empty, so it establishes nothing"));
        assert_eq!(got(first, path), want(set), "{path}[0] does not match `{set}`");
    }

    // The named-unknown state, wherever one appears. The reader enforces this shape exactly, so a
    // writer emitting `{state}` without a basis would be refused by every conforming reader.
    for path in ["bundle/content_hash", "bundle/source_revision", "source/source_revision"] {
        let node = path.split('/').fold(&m, |n, step| &n[step]);
        assert_eq!(got(node, path), want("unknown_state"), "{path} is not a named-unknown state");
    }

    // The bbox filter's shape, which the default whole-file case never exercises.
    assert_eq!(m["operation"]["filter"]["kind"], "covering-bbox-intersects");
    assert_eq!(
        got(&m["operation"]["filter"], "operation/filter"),
        want("filter_covering_bbox"),
        "the bbox filter does not match the shared key set"
    );

    // **`rows` is omitted on a viewer asset, not null.** The format has no meaning for a row count
    // on a JavaScript file, so the reader refuses one — which only works if the writer omits it.
    for asset in m["viewer"].as_array().unwrap() {
        assert!(asset.get("rows").is_none(), "a viewer asset carries `rows`");
    }
    // …and every partition carries one, as a non-negative integer, as does `bytes`.
    for p in m["data"]["partitions"].as_array().unwrap() {
        assert!(p["rows"].is_u64(), "a partition's `rows` is not a non-negative integer");
        assert!(p["bytes"].is_u64(), "a partition's `bytes` is not a non-negative integer");
    }

    // The reservations are empty and unavailable in v1, which is what makes them reservations.
    assert!(m["derived_caches"].as_array().unwrap().is_empty());
    assert_eq!(m["query_surface"]["available"], serde_json::Value::Bool(false));

    // And the two shapes the first publish could not show, from a second with neither option.
    let plain = d.join("bundle-whole-file");
    publish(&request(&ds, &v, plain.clone()), &CancelToken::new(), None).unwrap();
    let w: serde_json::Value = serde_json::from_slice(&read(&plain, bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(
        got(&w["operation"]["filter"], "operation/filter"),
        want("filter_whole_file"),
        "the whole-file filter does not match the shared key set"
    );
    assert_eq!(got(&w["license"], "license"), want("license_not_declared"));

    // **The third license shape, from a source that declares its own terms.**
    //
    // It was reachable in the writer and exercised by nothing: no test constructed it, so the shape
    // could have drifted in the artifact and the reader together with both suites staying green and
    // a real source-declared bundle being misjudged. It needs a real footer, which is why the
    // fixture generator has a `LicenseMode` — the same reason it has `CrsMode` and `IdentityMode`.
    let src = d.join("licensed.parquet");
    write_geoparquet(
        &src,
        &FixtureSpec {
            features: 200,
            attributes: AttributeMode::CategoricalZone,
            license: LicenseMode::DeclaredBySource,
            ..Default::default()
        },
    )
    .unwrap();
    let licensed_ds = pinned(&src);
    let licensed = d.join("bundle-source-licensed");
    publish(&request(&licensed_ds, &v, licensed.clone()), &CancelToken::new(), None).unwrap();
    let l: serde_json::Value =
        serde_json::from_slice(&read(&licensed, bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(
        got(&l["license"], "license"),
        want("license_declared_by_source"),
        "a source-declared license does not match the shared key set"
    );
    assert_eq!(l["license"]["state"], "declared-by-source");
    // Carried verbatim: the engine reads a declared set of keys and interprets no license text.
    assert_eq!(l["license"]["license"], "CC-BY-4.0");
    assert_eq!(l["license"]["redistribution"], "permitted");

    // **A source that declares attribution and names no license.**
    //
    // The three footer keys are independent, so this is an ordinary shape rather than a corner, and
    // the same member set applies to it — only the *value* differs. It used to publish the invented
    // string `"(unnamed)"`; ADR-017 Corrigendum 1 makes it `null`, the absence itself.
    let unnamed_src = d.join("attribution-only.parquet");
    write_geoparquet(
        &unnamed_src,
        &FixtureSpec {
            features: 200,
            attributes: AttributeMode::CategoricalZone,
            license: LicenseMode::AttributionWithoutLicenseName,
            ..Default::default()
        },
    )
    .unwrap();
    let unnamed_ds = pinned(&unnamed_src);
    let unnamed = d.join("bundle-attribution-only");
    publish(&request(&unnamed_ds, &v, unnamed.clone()), &CancelToken::new(), None).unwrap();
    let u: serde_json::Value =
        serde_json::from_slice(&read(&unnamed, bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(
        got(&u["license"], "license"),
        want("license_declared_by_source"),
        "an unnamed source license changed the member set rather than only the value"
    );
    assert_eq!(u["license"]["state"], "declared-by-source");
    assert_eq!(
        u["license"]["license"],
        serde_json::Value::Null,
        "a placeholder was substituted for a license the source never named"
    );
    // The attribution that *was* declared survives — which is the whole reason this is a `null`
    // rather than a refusal.
    assert_eq!(u["license"]["attribution"], "(c) Example Cadastre");
    assert_eq!(u["license"]["redistribution"], "permitted");
    // …and nothing resembling a substituted name reached any byte of the manifest.
    let unnamed_text = String::from_utf8(read(&unnamed, bundle::MANIFEST_PATH)).unwrap();
    assert!(
        !unnamed_text.contains("unnamed"),
        "an invented license name reached the manifest"
    );
}

/// The emitted top-level members in **order**, which until ADR-017 Corrigendum 3 nothing asserted.
///
/// **Why sorted comparison is not enough.** Both conformance tests — this file's key-set test and
/// the viewer's — sort before comparing, so a writer that emitted `viewer_license` last would pass
/// both while §5's declared order said otherwise. That made the order a preference rather than a
/// property, and Corrigendum 3 rests on a *positional* argument: `viewer_license` sits immediately
/// after `viewer` so a reader parsing top to bottom already holds the list its `notice_path` must
/// be checked against.
///
/// §2 makes the order "the **schema-declared fixed order**", not a sort, and §12 promises a
/// byte-identical manifest — which is a claim about a byte sequence and therefore about this.
#[test]
fn the_manifest_emits_its_top_level_members_in_the_order_adr_017_declares() {
    let d = workspace("manifest-key-order");
    let ds = pinned(&fixture(&d, 60));
    let v = viewer();
    let dest = d.join("bundle");
    publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();

    // Read as raw text, not through a map: `serde_json::Value` is a `BTreeMap` by default and would
    // hand back the members alphabetically, testing serde's ordering rather than the writer's.
    let text = String::from_utf8(read(&dest, bundle::MANIFEST_PATH)).unwrap();
    const DECLARED: &[&str] = &[
        "bundle_version",
        "bundle",
        "source",
        "source_verification",
        "style",
        "software",
        "operation",
        "crs",
        "identity",
        "schema",
        "bounds",
        "data",
        "viewer",
        "viewer_license",
        "license",
        "reproducibility",
        "derived_caches",
        "query_surface",
        "sidecar",
    ];

    // Each member's key, at the top level, is `"name":` preceded by `{` or `,`. Nested objects
    // reuse some of these names (`license` appears inside `viewer_license`, `source` inside `crs`),
    // so the search walks forward from the previous member's position and requires each to appear
    // after the last — which is what "in order" means and what a naive `find` would not establish.
    let mut cursor = 0usize;
    let mut previous = "";
    for name in DECLARED {
        let needle = format!("\"{name}\":");
        let at = text[cursor..].find(&needle).unwrap_or_else(|| {
            panic!("`{name}` does not appear after `{previous}` in the emitted manifest")
        });
        cursor += at + needle.len();
        previous = name;
    }

    // …and the first member really is first, so the walk above cannot be satisfied by a manifest
    // that merely happens to contain the names somewhere in that relative order.
    assert!(
        text.starts_with("{\"bundle_version\":"),
        "the manifest does not open with `bundle_version`: {}",
        &text[..text.len().min(60)]
    );
}

/// `viewer_license` carries the distributed code's terms, and `notice_path` names a **hash-listed**
/// viewer asset in the **bundle-relative** namespace (ADR-009 item 7; ADR-017 Corrigendum 3).
///
/// The namespace translation is the substance: the caller supplies `NOTICE.txt` (viewer-relative,
/// as every `ViewerAsset::path` is) and the manifest must carry `viewer/NOTICE.txt`, because §14
/// requires every asset path to be bundle-relative and a reader can cross-check only against what
/// the manifest actually contains.
#[test]
fn the_viewer_licence_notice_names_a_hash_listed_asset_in_the_bundle_relative_namespace() {
    let d = workspace("viewer-license");
    let ds = pinned(&fixture(&d, 60));
    let v = viewer();
    let dest = d.join("bundle");
    publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap();
    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();

    let vl = &m["viewer_license"];
    assert_eq!(vl["program"], "Spatial IDE bundle viewer");
    assert_eq!(vl["license"], "AGPL-3.0-or-later");
    assert!(vl["copyright"].as_str().unwrap().contains("Copyright (C) 2026"));

    // Translated on the way out, not carried through.
    assert_eq!(
        vl["notice_path"], "viewer/NOTICE.txt",
        "the notice path was not translated into the bundle-relative namespace"
    );

    // …and it names an entry that is actually in `viewer[]`, with a content hash. This is the
    // relation a conforming reader checks, asserted here from the writing side.
    let listed = m["viewer"]
        .as_array()
        .unwrap()
        .iter()
        .find(|a| a["path"] == vl["notice_path"])
        .expect("notice_path names no entry in viewer[]");
    assert!(
        listed["content_hash"].as_str().unwrap().starts_with("sha256:"),
        "the notice is listed without a content hash"
    );
    assert!(dest.join("viewer/NOTICE.txt").is_file(), "the notice file is not in the bundle");

    // The route, and the fixed note quoted verbatim in Corrigendum 3. The note is checked against
    // the constant rather than against a literal here, so the ADR, the writer and this test cannot
    // drift into three wordings — the ADR quotes the constant, and this asserts the constant ships.
    assert_eq!(vl["corresponding_source"]["kind"], "url");
    assert_eq!(vl["corresponding_source"]["at"], "https://example.invalid/spatial-ide");
    assert_eq!(vl["corresponding_source"]["note"], bundle::CORRESPONDING_SOURCE_NOTE);
    // It says what it does not establish, which is the whole reason it is a fixed string.
    assert!(vl["corresponding_source"]["note"]
        .as_str()
        .unwrap()
        .contains("a route recorded, not a guarantee"));
}

/// The three `viewer_license` refusals, each producing **no bundle at all**.
///
/// ADR-009 item 7 says *every* bundle carries the notice and the route. That is a property of the
/// operation only if the operation refuses to produce one otherwise — so each case here asserts the
/// typed error **and** that the destination does not exist, which is the part that makes the
/// guarantee real rather than advisory.
#[test]
fn a_bundle_that_cannot_carry_the_distributed_codes_terms_is_not_produced_at_all() {
    let d = workspace("viewer-license-refusals");
    let ds = pinned(&fixture(&d, 60));
    let v = viewer();

    // 1. A blank member. Every one of the five is checked, because a loop that tested only the
    //    first would leave four fields whose emptiness nothing refuses.
    for (n, blank) in [
        ("program", 0usize),
        ("copyright", 1),
        ("license", 2),
        ("notice_path", 3),
        ("corresponding_source.at", 4),
    ] {
        let dest = d.join(format!("blank-{n}"));
        let mut req = request(&ds, &v, dest.clone());
        match blank {
            0 => req.viewer_license.program = "   ".into(),
            1 => req.viewer_license.copyright = String::new(),
            2 => req.viewer_license.license = "\t".into(),
            3 => req.viewer_license.notice_path = String::new(),
            _ => req.viewer_license.corresponding_source.at = "  ".into(),
        }
        let e = publish(&req, &CancelToken::new(), None).unwrap_err();
        assert!(
            matches!(e, PublishError::ViewerLicenseIncomplete { member } if member == n),
            "a blank `{n}` produced {e:?}"
        );
        assert!(!dest.exists(), "a bundle exists despite a blank `{n}`");
    }

    // 2. A notice path naming no viewer asset. The declaration would point at nothing, and the
    //    bundle would be refused by every conforming reader — so it is refused here instead.
    let dest = d.join("missing-notice");
    let mut req = request(&ds, &v, dest.clone());
    req.viewer_license.notice_path = "NOTICE-THAT-IS-NOT-THERE.txt".into();
    let e = publish(&req, &CancelToken::new(), None).unwrap_err();
    match &e {
        PublishError::ViewerLicenseNoticeMissing { notice_path, bundle_relative, available } => {
            // **Both namespaces are reported**, because confusing them is the mistake this refusal
            // exists to catch and a message naming only one would not tell the operator which.
            assert_eq!(notice_path, "NOTICE-THAT-IS-NOT-THERE.txt");
            assert_eq!(bundle_relative, "viewer/NOTICE-THAT-IS-NOT-THERE.txt");
            assert!(available.iter().any(|p| p == "NOTICE.txt"), "{available:?}");
        }
        other => panic!("a notice path naming nothing produced {other:?}"),
    }
    assert!(!dest.exists(), "a bundle exists despite a notice path naming nothing");

    // 3. A `url` route that no recipient could follow. A `file://` route is both a docs/09
    //    redaction leak and not durable in ADR-009 item 7's sense.
    for bad in ["file:///C:/dev/spatial-ide", "C:\\dev\\spatial-ide", "spatial-ide", "ftp://x/y"] {
        let dest = d.join("bad-route");
        let mut req = request(&ds, &v, dest.clone());
        req.viewer_license.corresponding_source.at = bad.into();
        let e = publish(&req, &CancelToken::new(), None).unwrap_err();
        assert!(
            matches!(e, PublishError::CorrespondingSourceNotDurable { .. }),
            "`{bad}` was admitted as a url route: {e:?}"
        );
        assert!(!dest.exists());
    }

    // …and a `written-offer` is **not** scheme-checked, because there is no scheme to check. The
    // check must not have become "every route must look like a URL".
    let dest = d.join("written-offer");
    let mut req = request(&ds, &v, dest.clone());
    req.viewer_license.corresponding_source = CorrespondingSource {
        kind: CorrespondingSourceKind::WrittenOffer,
        at: "Write to the address in the notice file for a copy of the source, valid three years."
            .into(),
    };
    publish(&req, &CancelToken::new(), None).unwrap();
    let m: serde_json::Value = serde_json::from_slice(&read(&dest, bundle::MANIFEST_PATH)).unwrap();
    assert_eq!(m["viewer_license"]["corresponding_source"]["kind"], "written-offer");
}

/// A source whose own terms forbid redistribution is refused, because a static bundle **is** a
/// redistributed copy (ADR-006 class 3; `docs/09`).
///
/// The refusal existed and was unit-tested against a hand-built `SourceLicense`; this is the first
/// test that reaches it through a **real parquet footer**, which is the path a real source takes.
#[test]
fn a_source_that_forbids_redistribution_is_refused_before_anything_is_written() {
    let d = workspace("license-forbidden");
    let src = d.join("forbidden.parquet");
    write_geoparquet(
        &src,
        &FixtureSpec {
            features: 100,
            attributes: AttributeMode::CategoricalZone,
            license: LicenseMode::ForbidsRedistribution,
            ..Default::default()
        },
    )
    .unwrap();
    let ds = pinned(&src);
    let v = viewer();
    let dest = d.join("bundle");
    match publish(&request(&ds, &v, dest.clone()), &CancelToken::new(), None).unwrap_err() {
        PublishError::LicenseNotCarryable { declared_by, redistribution } => {
            assert_eq!(declared_by, "source");
            assert_eq!(redistribution, "forbidden");
        }
        other => panic!("expected LicenseNotCarryable, got {other}"),
    }
    assert!(!dest.exists(), "a bundle was written for a source that forbids redistribution");
}
