// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

//! **The `publish-bundle` binary itself**, driven the way an operator drives it.
//!
//! ## Why this file exists at all
//!
//! `publish.rs` exercises the publish *library* thoroughly, and every viewport-CRS rule ADR-015 §7
//! states is already asserted against the *engine* in `engine/tests/slice.rs`. Both suites were
//! green while `publish-bundle --bbox` was refusing a whole source kind outright, because the defect
//! was in neither: it was in how the binary **composed** them. The CLI built a `ViewportQuery` whose
//! `bbox_crs` echoed `dataset.crs().identifier()`, and nothing tested the binary.
//!
//! A composition root that no test drives is a place where two correct modules can be wired together
//! wrongly and every suite stays green. So these tests run the built binary as a subprocess and read
//! the bundle it wrote off the disk.
//!
//! ## The rule being asserted, stated once
//!
//! ADR-015 §7: a viewport CRS identifier is a **caller assertion about the query**, and a viewport
//! sent with **no** CRS declares that its coordinates are already in the dataset's own. `--bbox`
//! carries no CRS, so it means exactly the second thing and the manifest records `bbox_crs: null`.
//!
//! Echoing the dataset's own identifier back was wrong on both source kinds, which is why both are
//! covered here:
//!
//! - **authority-identified** (`EPSG:2056`) — the echo manufactured a caller assertion the caller
//!   never made, out of the very value it would then be compared against. It could not fail, so it
//!   established nothing, and it wrote a claim into `operation.filter.bbox_crs` that no operator had
//!   asserted.
//! - **definition-only** — every such dataset shares the `(definition-only)` placeholder, and §7.3
//!   refuses a viewport that names it (`ViewportCrsUnidentifiable`). The echo therefore made `--bbox`
//!   **unusable on that entire source kind**, for a reason no operator could read off the command
//!   line. That test would have failed before this fix; it is the regression this file exists for.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use spatial_engine::fixture::{write_geoparquet, AttributeMode, CrsMode, FixtureSpec};

/// A style over the fixture's `zone` column, so the publish exercises the ordinary path rather than
/// a degenerate one.
const STYLE: &str = r##"{
  "style_version": 1,
  "layer": {
    "geometry": "polygon",
    "fill_color": {"match": {
      "column": "zone",
      "cases": [{"when": "residential", "then": "#aa3333"},
                {"when": "industrial",  "then": "#333388"}],
      "on_null": "#888888",
      "on_unmatched": "#cccccc"}},
    "fill_opacity": {"literal": 0.8},
    "outline_color": {"literal": "#202020"},
    "outline_width": {"literal": 1.0}
  }
}"##;

/// The fixture's grid is 40 m per cell from `(E_LO, N_LO)`, so this window covers a subset of a
/// 2 000-feature fixture rather than all of it or none of it. Both are asserted, because a filter
/// that selected everything would make "the filter was applied" unfalsifiable.
const FEATURES: usize = 2_000;
const WINDOW: f64 = 600.0;

fn workspace(name: &str) -> PathBuf {
    let d = std::env::temp_dir().join("spatial-kernel-publish-cli-tests").join(name);
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn fixture(dir: &Path, crs_mode: CrsMode) -> PathBuf {
    let path = dir.join("parcels.parquet");
    write_geoparquet(
        &path,
        &FixtureSpec {
            features: FEATURES,
            attributes: AttributeMode::CategoricalZone,
            crs_mode,
            ..Default::default()
        },
    )
    .unwrap();
    path
}

fn style_file(dir: &Path) -> PathBuf {
    let path = dir.join("style.json");
    std::fs::write(&path, STYLE).unwrap();
    path
}

/// A viewer directory rather than `ViewerAssets`: the binary takes `--viewer <dir>` and reads it,
/// and that read is part of what these tests are driving.
fn viewer_dir(dir: &Path) -> PathBuf {
    let path = dir.join("viewer");
    std::fs::create_dir_all(&path).unwrap();
    std::fs::write(path.join("index.html"), b"<!doctype html><title>t</title>").unwrap();
    std::fs::write(path.join("app.js"), b"export const ok = 1;\n").unwrap();
    // The notice `--viewer-notice` names. Required in every bundle by ADR-009 item 7; the real one
    // is generated by `renderer/bundle-viewer/build.mjs` and reaches the acceptance run.
    std::fs::write(path.join("NOTICE.txt"), b"stub notice\n").unwrap();
    path
}

/// The five arguments ADR-009 item 7 makes mandatory, as an operator would type them.
///
/// Spliced in by [`publish_bundle`] rather than repeated at each call site: every test in this file
/// publishes, none of them is *about* these flags, and five more lines per invocation would bury
/// the argument each test actually exercises. The test that **is** about them uses
/// [`publish_bundle_raw`].
const VIEWER_LICENSE_ARGS: &[&str] = &[
    "--viewer-program",
    "Spatial IDE bundle viewer",
    "--viewer-copyright",
    "Copyright (C) 2026 the Spatial IDE contributors",
    "--viewer-license",
    "AGPL-3.0-or-later",
    "--viewer-notice",
    "NOTICE.txt",
    "--corresponding-source-url",
    "https://example.invalid/spatial-ide",
];

/// Run the built binary with the mandatory viewer-license arguments **and an approval** appended.
///
/// **The binary, not a re-implementation of its argument handling** — the defect this file covers
/// lived in argument handling.
///
/// The approval is spliced in for the same reason the viewer-license arguments are: publishing is a
/// class-3 side effect and every run through this harness must pass the gate, but none of these
/// tests is *about* the gate — `kernel/tests/permission_boundary.rs` is. The value is derived from
/// `--out` rather than hardcoded, so a test that changes its destination cannot silently start
/// approving the wrong one; that is exactly the staleness the named confirmation exists to catch,
/// and a harness that defeated it would be testing nothing.
fn publish_bundle(args: &[&str]) -> Output {
    let mut all: Vec<&str> = args.to_vec();
    all.extend_from_slice(VIEWER_LICENSE_ARGS);
    let approve = out_basename(args)
        .expect("every test that publishes passes --out, and the approval is derived from it");
    all.push("--approve");
    all.push(&approve);
    publish_bundle_raw(&all)
}

/// The final path component of this invocation's `--out`, which is what `--approve` must name.
fn out_basename(args: &[&str]) -> Option<String> {
    let i = args.iter().position(|a| *a == "--out")?;
    Path::new(args.get(i + 1)?).file_name().map(|n| n.to_string_lossy().to_string())
}

/// Run the binary with **exactly** these arguments and nothing added.
///
/// The one thing that *is* always set is `SPATIAL_IDE_AUDIT_LOG`. It is not an argument — it is
/// containment: without it a test run would append class-3 records to the operator's own audit log
/// in `%LOCALAPPDATA%`, which is somebody's real record of real publishes and not a scratch file.
fn publish_bundle_raw(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_publish-bundle"))
        .env(
            spatial_kernel::permission::AUDIT_LOG_ENV,
            std::env::temp_dir()
                .join("spatial-kernel-publish-cli-tests")
                .join("audit.jsonl"),
        )
        .args(args)
        .output()
        .expect("run publish-bundle")
}

fn assert_ok(out: &Output, what: &str) {
    assert!(
        out.status.success(),
        "{what} failed with {}\n--- stdout ---\n{}\n--- stderr ---\n{}",
        out.status,
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
}

fn manifest(bundle: &Path) -> serde_json::Value {
    let bytes = std::fs::read(bundle.join(spatial_kernel::bundle::MANIFEST_PATH))
        .expect("the bundle has a manifest");
    serde_json::from_slice(&bytes).expect("the manifest is JSON")
}

/// The `--bbox` window for a fixture, in that fixture's own coordinates.
fn bbox_arg() -> String {
    let (e, n) = (spatial_engine::fixture::E_LO, spatial_engine::fixture::N_LO);
    format!("{e},{n},{},{}", e + WINDOW, n + WINDOW)
}

/// Common assertions over a `--bbox` publish, so the two source kinds differ only in the fixture.
fn assert_bbox_filter_carries_no_caller_assertion(bundle: &Path) {
    let m = manifest(bundle);
    let filter = &m["operation"]["filter"];
    assert_eq!(
        filter["kind"].as_str().unwrap(),
        "covering-bbox-intersects",
        "the filter is not the one `--bbox` asks for"
    );
    // **The assertion this file exists for.** `null`, not the dataset's identifier: the operator
    // asserted nothing, so the manifest records nothing (ADR-015 §7; ADR-017 §6 lists
    // `operation.filter.bbox_crs` among the members whose bare `null` means "absent").
    assert_eq!(
        filter["bbox_crs"],
        serde_json::Value::Null,
        "`bbox_crs` echoes an assertion the operator never made: {}",
        filter["bbox_crs"]
    );
    // **The window the operator typed is the window the manifest records.** Checked because the
    // defect this file covers was in argument handling, and `--bbox` parsing is where a component
    // can go missing — see `a_bbox_with_an_unparseable_component_is_refused_rather_than_dropped`.
    let (e, n) = (spatial_engine::fixture::E_LO, spatial_engine::fixture::N_LO);
    for (member, want) in
        [("xmin", e), ("ymin", n), ("xmax", e + WINDOW), ("ymax", n + WINDOW)]
    {
        assert_eq!(
            filter[member].as_f64().unwrap(),
            want,
            "the manifest's filter.{member} is not the value `--bbox` was given"
        );
    }

    // The filter really ran: some rows were excluded, and some survived. Without both halves a
    // `bbox_crs` of `null` could be true of a publish that quietly ignored `--bbox` entirely.
    let rows = m["data"]["rows"].as_u64().unwrap();
    assert!(rows > 0, "the viewport selected nothing, so the publish proves nothing");
    assert!(
        rows < FEATURES as u64,
        "the viewport selected all {FEATURES} features, so no filtering is demonstrated"
    );
}

/// The authority-identified case: the echo was admissible here, and still wrong.
#[test]
fn a_bbox_publish_on_an_authority_identified_source_records_no_caller_assertion() {
    let d = workspace("authority-identified");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let dest = d.join("bundle");

    let out = publish_bundle(&[
        "--data",
        src.to_str().unwrap(),
        "--style",
        style_file(&d).to_str().unwrap(),
        "--viewer",
        viewer_dir(&d).to_str().unwrap(),
        "--out",
        dest.to_str().unwrap(),
        "--attributes",
        "zone",
        "--bbox",
        &bbox_arg(),
    ]);
    assert_ok(&out, "a --bbox publish on an authority-identified source");

    // The fixture really is the source kind this test names — otherwise the two tests below could
    // both be running against the same file and one of them would be decorative.
    assert_eq!(manifest(&dest)["crs"]["source"].as_str().unwrap(), "EPSG:2056");
    assert_bbox_filter_carries_no_caller_assertion(&dest);
}

/// The definition-only case: **this publish was impossible before the fix.**
///
/// `dataset.crs().identifier()` is the `(definition-only)` placeholder here, and ADR-015 §7.3
/// refuses a viewport that names it — so the binary's own echo made the engine refuse the binary's
/// own query, and `--bbox` had no working form at all on this source kind.
#[test]
fn a_bbox_publish_on_a_definition_only_source_is_possible_at_all() {
    let d = workspace("definition-only");
    let src = fixture(&d, CrsMode::DefinitionOnlyNoId);
    let dest = d.join("bundle");

    let out = publish_bundle(&[
        "--data",
        src.to_str().unwrap(),
        "--style",
        style_file(&d).to_str().unwrap(),
        "--viewer",
        viewer_dir(&d).to_str().unwrap(),
        "--out",
        dest.to_str().unwrap(),
        "--attributes",
        "zone",
        "--bbox",
        &bbox_arg(),
    ]);
    assert_ok(&out, "a --bbox publish on a definition-only source");

    // The fixture really is definition-only: this is the placeholder every such dataset shares, and
    // the reason §7.3 refuses a viewport that echoes it.
    assert_eq!(
        manifest(&dest)["crs"]["source"].as_str().unwrap(),
        spatial_engine::crs::DEFINITION_ONLY,
        "this fixture is not the definition-only source kind, so this test asserts nothing"
    );
    assert_bbox_filter_carries_no_caller_assertion(&dest);
}

/// **A `--bbox` component that is not a number refuses the publish rather than being dropped.**
///
/// The parser was `split(',').filter_map(|s| s.parse().ok())` followed by a length check, so a
/// malformed component vanished and any four surviving numbers became the window: `--bbox
/// junk,A,B,C,D` published `A,B,C,D` — a query the operator never asked for, irreversibly, with no
/// word said. A dropped argument is a different operation, and this binary performs a class-3
/// external side effect.
#[test]
fn a_bbox_with_an_unparseable_component_is_refused_rather_than_dropped() {
    let d = workspace("bbox-malformed");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let style = style_file(&d);
    let viewer = viewer_dir(&d);
    let (e, n) = (spatial_engine::fixture::E_LO, spatial_engine::fixture::N_LO);

    // Five fields, one of them junk: exactly the shape that used to collapse to a valid-looking
    // four-number window.
    let smuggled = format!("junk,{e},{n},{},{}", e + WINDOW, n + WINDOW);
    for bad in [smuggled.as_str(), "1,2,3", "1,2,3,4,5", "1,2,3,x", ""] {
        let dest = d.join(format!("bundle-{}", bad.len()));
        let out = publish_bundle(&[
            "--data",
            src.to_str().unwrap(),
            "--style",
            style.to_str().unwrap(),
            "--viewer",
            viewer.to_str().unwrap(),
            "--out",
            dest.to_str().unwrap(),
            "--attributes",
            "zone",
            "--bbox",
            bad,
        ]);
        assert!(
            !out.status.success(),
            "`--bbox {bad}` was accepted; stdout:\n{}",
            String::from_utf8_lossy(&out.stdout)
        );
        assert!(!dest.exists(), "`--bbox {bad}` wrote a bundle before failing");
    }
}

/// **`--license` without `--license-at` is refused, and the tool never substitutes its own clock.**
///
/// ADR-017 §10 makes `license.at` the instant the **operator made the declaration** and §12 keeps
/// **build** timing out of the manifest entirely. This binary passed its own `started_at` — the
/// build clock — as `license.at`, which put a value the manifest cannot support into the manifest
/// *and* made every operator-declared publish produce different bytes on every run, breaking §12's
/// byte-identity guarantee for that whole branch.
#[test]
fn an_operator_license_requires_its_declaration_instant_and_never_borrows_the_build_clock() {
    let d = workspace("license-at");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let style = style_file(&d);
    let viewer = viewer_dir(&d);
    let base = |dest: &str| -> Vec<String> {
        vec![
            "--data".into(),
            src.to_str().unwrap().into(),
            "--style".into(),
            style.to_str().unwrap().into(),
            "--viewer".into(),
            viewer.to_str().unwrap().into(),
            "--out".into(),
            d.join(dest).to_str().unwrap().into(),
            "--attributes".into(),
            "zone".into(),
        ]
    };
    let run = |args: Vec<String>| {
        publish_bundle(&args.iter().map(String::as_str).collect::<Vec<_>>())
    };

    // Refused, and nothing is written.
    let mut without = base("no-at");
    without.extend(["--license".into(), "CC-BY-4.0".into()]);
    let out = run(without);
    assert!(!out.status.success(), "--license without --license-at published anyway");
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("--license-at"),
        "the refusal does not name the missing flag"
    );
    assert!(!d.join("no-at").exists());

    // The reverse is refused too: there is no manifest state for "declared nothing, at 09:00".
    let mut orphan = base("orphan-at");
    orphan.extend(["--license-at".into(), "2026-08-06T09:00:00Z".into()]);
    assert!(!run(orphan).status.success(), "--license-at without --license published anyway");

    // A blank license is refused at the library choke point as well as here.
    let mut blank = base("blank");
    blank.extend([
        "--license".into(),
        "   ".into(),
        "--license-at".into(),
        "2026-08-06T09:00:00Z".into(),
    ]);
    assert!(!run(blank).status.success(), "a blank --license published anyway");

    // …and a complete declaration publishes, carrying **the declared instant**, not the build's.
    let mut ok = base("declared");
    ok.extend([
        "--license".into(),
        "CC-BY-4.0".into(),
        "--license-at".into(),
        "2026-08-06T09:00:00Z".into(),
        "--attribution".into(),
        "(c) Example Cadastre".into(),
        "--redistribution".into(),
        "permitted".into(),
    ]);
    let out = run(ok);
    assert_ok(&out, "a complete operator declaration");
    let m = manifest(&d.join("declared"));
    assert_eq!(m["license"]["state"].as_str().unwrap(), "declared-by-operator");
    assert_eq!(m["license"]["license"].as_str().unwrap(), "CC-BY-4.0");
    assert_eq!(
        m["license"]["at"].as_str().unwrap(),
        "2026-08-06T09:00:00Z",
        "`license.at` is not the instant the operator declared"
    );
    // The build clock lives in the sidecar, and the two are different values. A build that started
    // at the declared instant to the second would make this vacuous, which no real run does.
    let sidecar: serde_json::Value =
        serde_json::from_slice(&std::fs::read(d.join("declared").join("build-info.json")).unwrap())
            .unwrap();
    assert_ne!(
        sidecar["started_at"].as_str().unwrap(),
        "2026-08-06T09:00:00Z",
        "the build clock and the declaration instant are the same value again"
    );
}

/// A publish with no `--bbox` still records `whole-file`, so the fix did not turn every publish into
/// a filtered one with an absent CRS.
#[test]
fn a_publish_without_a_bbox_still_records_the_whole_file_filter() {
    let d = workspace("whole-file");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let dest = d.join("bundle");

    let out = publish_bundle(&[
        "--data",
        src.to_str().unwrap(),
        "--style",
        style_file(&d).to_str().unwrap(),
        "--viewer",
        viewer_dir(&d).to_str().unwrap(),
        "--out",
        dest.to_str().unwrap(),
        "--attributes",
        "zone",
    ]);
    assert_ok(&out, "a whole-file publish");

    let m = manifest(&dest);
    assert_eq!(m["operation"]["filter"]["kind"].as_str().unwrap(), "whole-file");
    // §8 gives `whole-file` exactly one member; a `bbox_crs` here would be a key the format does not
    // define in that shape, and every conforming reader would refuse the bundle.
    assert!(m["operation"]["filter"].get("bbox_crs").is_none());
    assert_eq!(m["data"]["rows"].as_u64().unwrap(), FEATURES as u64);
}

/// **The five mandatory arguments are mandatory at the command line too**, and the refusal explains
/// the obligation rather than only naming the missing flag.
///
/// ADR-009 item 7 requires every bundle to carry the distributed code's notice and a
/// corresponding-source route, and ADR-017 Corrigendum 3 makes that a property of the publish
/// operation. The library refuses for every caller; this asserts the binary does not paper over it
/// with a default, which is exactly the kind of convenience that would make the guarantee untrue
/// for the one caller an operator actually uses.
#[test]
fn the_binary_refuses_to_publish_without_the_distributed_codes_terms() {
    let d = workspace("viewer-license-cli");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let viewer = viewer_dir(&d);
    let style = style_file(&d);

    let base = |dest: &Path| -> Vec<String> {
        vec![
            "--data".into(),
            src.to_str().unwrap().into(),
            "--style".into(),
            style.to_str().unwrap().into(),
            "--viewer".into(),
            viewer.to_str().unwrap().into(),
            "--out".into(),
            dest.to_str().unwrap().into(),
            "--attributes".into(),
            "zone".into(),
        ]
    };

    // Each flag omitted in turn, so a refusal covering only the first would be caught.
    for (i, (flag, expect)) in [
        ("--viewer-program", "--viewer-program is required"),
        ("--viewer-copyright", "--viewer-copyright is required"),
        ("--viewer-license", "--viewer-license is required"),
        ("--viewer-notice", "--viewer-notice is required"),
        ("--corresponding-source-url", "--corresponding-source-url or"),
    ]
    .into_iter()
    .enumerate()
    {
        let dest = d.join(format!("omitted-{i}"));
        let mut args = base(&dest);
        // Every mandatory pair except the one under test.
        let mut it = VIEWER_LICENSE_ARGS.iter();
        while let (Some(f), Some(v)) = (it.next(), it.next()) {
            if *f == flag {
                continue;
            }
            args.push((*f).to_string());
            args.push((*v).to_string());
        }
        let refs: Vec<&str> = args.iter().map(String::as_str).collect();
        let out = publish_bundle_raw(&refs);
        assert!(!out.status.success(), "publishing without {flag} succeeded");
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(stderr.contains(expect), "omitting {flag} said: {stderr}");
        // The refusal names the obligation, not merely the flag — an operator meeting these for the
        // first time needs to know they are discharging a license requirement.
        assert!(
            stderr.contains("ADR-009 item 7") || stderr.contains("Corrigendum 3"),
            "the refusal for {flag} does not say why the argument exists: {stderr}"
        );
        assert!(!dest.exists(), "a bundle exists despite a missing {flag}");
    }

    // …and the two route flags are mutually exclusive rather than last-one-wins: a bundle carries
    // one route, and choosing between two operator statements is not the tool's call.
    let dest = d.join("both-routes");
    let mut args = base(&dest);
    for a in VIEWER_LICENSE_ARGS {
        args.push((*a).to_string());
    }
    args.push("--corresponding-source-offer".into());
    args.push("Write to the address in the notice file.".into());
    let refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let out = publish_bundle_raw(&refs);
    assert!(!out.status.success(), "both route flags together were accepted");
    assert!(String::from_utf8_lossy(&out.stderr).contains("mutually exclusive"));
    assert!(!dest.exists());
}

// ---- the class-3 gate, at the binary ------------------------------------------------------------

/// Run the binary with `stdin` scripted, so the **interactive** approval path is exercised for real.
///
/// `kernel/tests/permission_boundary.rs` drives `ApprovalSource` directly, which covers the
/// comparison but not `StdinApproval` itself — the thing that actually reads a console. Piping is
/// what makes that path deterministic: the process gets exactly these bytes and then EOF.
fn publish_bundle_with_stdin(args: &[&str], stdin: &str) -> Output {
    use std::io::Write as _;
    use std::process::Stdio;

    let mut all: Vec<&str> = args.to_vec();
    all.extend_from_slice(VIEWER_LICENSE_ARGS);

    let mut child = Command::new(env!("CARGO_BIN_EXE_publish-bundle"))
        .env(
            spatial_kernel::permission::AUDIT_LOG_ENV,
            std::env::temp_dir().join("spatial-kernel-publish-cli-tests").join("audit.jsonl"),
        )
        .args(&all)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn publish-bundle");
    child
        .stdin
        .as_mut()
        .expect("stdin is piped")
        .write_all(stdin.as_bytes())
        .expect("write stdin");
    // Dropping the handle closes the pipe, so an empty `stdin` reaches the binary as EOF — which is
    // the case the "refusal is the default on EOF" rule is about.
    drop(child.stdin.take());
    child.wait_with_output().expect("wait for publish-bundle")
}

/// **The interactive path, end to end.** Typing the destination's name approves; anything else, and
/// end-of-input, refuse — with no bundle left behind.
///
/// Publishing is irreversible, so the default on every input that is not the exact phrase must be
/// refusal (ADR-006 class 3; `docs/09`). The three refusal cases are the ones an operator or a
/// script actually produces: the `y` reflex, a stale name, and a closed pipe.
#[test]
fn the_interactive_approval_requires_the_destination_name_and_refuses_everything_else() {
    let d = workspace("interactive-approval");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let style = style_file(&d);
    let viewer = viewer_dir(&d);

    let args = |dest: &Path| -> Vec<String> {
        vec![
            "--data".into(), src.to_str().unwrap().into(),
            "--style".into(), style.to_str().unwrap().into(),
            "--viewer".into(), viewer.to_str().unwrap().into(),
            "--out".into(), dest.to_str().unwrap().into(),
            "--attributes".into(), "zone".into(),
        ]
    };

    // ---- the refusals ----
    for (case, typed) in [("bare-yes", "y\n"), ("wrong-name", "some-other-bundle\n"), ("eof", "")] {
        let dest = d.join(format!("refused-{case}"));
        let a = args(&dest);
        let refs: Vec<&str> = a.iter().map(String::as_str).collect();
        let out = publish_bundle_with_stdin(&refs, typed);

        assert!(
            !out.status.success(),
            "{case}: the binary published on an input that is not the destination's name"
        );
        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(
            stderr.contains("refused"),
            "{case}: the refusal is not reported as one: {stderr}"
        );
        assert!(!dest.exists(), "{case}: a bundle exists despite the refusal");
        // The prompt showed the operator what they were being asked about, before they answered.
        assert!(
            stderr.contains("irreversible") && stderr.contains("approval required"),
            "{case}: the operator was not shown the class-3 prompt: {stderr}"
        );
    }

    // ---- the approval ----
    let dest = d.join("approved-bundle");
    let a = args(&dest);
    let refs: Vec<&str> = a.iter().map(String::as_str).collect();
    let out = publish_bundle_with_stdin(&refs, "approved-bundle\n");
    assert_ok(&out, "an interactive publish approved by naming the destination");
    assert!(dest.join("manifest.json").exists(), "the approved publish produced no bundle");
}

/// `--approve` must name **this** destination, so a script that outlived an `--out` change is
/// refused rather than silently approving something else.
#[test]
fn an_approve_flag_naming_a_different_destination_is_refused() {
    let d = workspace("stale-approve");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let dest = d.join("bundle");

    let mut args: Vec<String> = vec![
        "--data".into(), src.to_str().unwrap().into(),
        "--style".into(), style_file(&d).to_str().unwrap().into(),
        "--viewer".into(), viewer_dir(&d).to_str().unwrap().into(),
        "--out".into(), dest.to_str().unwrap().into(),
        "--attributes".into(), "zone".into(),
        // The name of a destination this run is not publishing to.
        "--approve".into(), "yesterdays-bundle".into(),
    ];
    for a in VIEWER_LICENSE_ARGS {
        args.push((*a).to_string());
    }
    let refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let out = publish_bundle_raw(&refs);

    assert!(!out.status.success(), "a stale --approve was accepted");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("bundle"), "the refusal does not name what was expected: {stderr}");
    assert!(!dest.exists(), "a bundle exists despite a mismatched --approve");
}

/// A grant scoped to a **directory** covers a publish into it, which is the one part of the
/// binary's self-minted grant that is not a tautology.
#[test]
fn a_directory_scoped_grant_covers_a_publish_into_that_directory() {
    let d = workspace("grant-destination");
    let src = fixture(&d, CrsMode::DeclaredLv95);
    let target_dir = d.join("published");
    std::fs::create_dir_all(&target_dir).unwrap();
    let dest = target_dir.join("bundle");

    let out = publish_bundle(&[
        "--data", src.to_str().unwrap(),
        "--style", style_file(&d).to_str().unwrap(),
        "--viewer", viewer_dir(&d).to_str().unwrap(),
        "--out", dest.to_str().unwrap(),
        "--attributes", "zone",
        "--grant-destination", target_dir.to_str().unwrap(),
    ]);
    assert_ok(&out, "a publish into a directory-scoped grant's directory");
    assert!(dest.join("manifest.json").exists());

    // …and the same grant does not cover a publish somewhere else. The grant names `published/`;
    // this `--out` is a sibling of it, so the scope check refuses before anything is created.
    let elsewhere = d.join("elsewhere");
    let out = publish_bundle(&[
        "--data", src.to_str().unwrap(),
        "--style", style_file(&d).to_str().unwrap(),
        "--viewer", viewer_dir(&d).to_str().unwrap(),
        "--out", elsewhere.to_str().unwrap(),
        "--attributes", "zone",
        "--grant-destination", target_dir.to_str().unwrap(),
    ]);
    assert!(!out.status.success(), "a directory-scoped grant covered a publish outside it");
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("does not cover"),
        "the refusal is not the scope one: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(!elsewhere.exists());
}
