// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

//! **The 5 GB scale pass**, as a committed, re-runnable harness.
//!
//! ```bash
//! cargo test --release -p spatial-kernel --test scale_pass -- --ignored --nocapture
//! ```
//!
//! `#[ignore]`d: it generates ~5 GB, publishes ~5.7 GB twice, and runs for the better part of an
//! hour. It refuses to run on a debug build.
//!
//! **Everything it does is pre-registered in `kernel/SCALE-PASS-PREREGISTRATION.md`**, which was
//! committed before this file existed and before the fixture existed. Where a number appears here
//! it is because that file declared it; where a ceiling appears here it is because that file
//! declared it. Changing either after a result has been seen invalidates the run.
//!
//! ## The cold-open row is not here
//!
//! It needs three reboots and an operator. `kernel/scripts/cold-open.ps1` is that phase, and it runs
//! **after** everything in this file — decided with the human before any measurement, because a
//! reboot re-evicts the cache anyway and an operator's window should not be spent on a pass that
//! might invalidate earlier.
//!
//! ## What this harness may and may not be used for
//!
//! - **Every comparison is within-session.** The canary is taken at each phase boundary; a spread
//!   beyond the declared 10 % invalidates that phase.
//! - **No throughput claim.** Bytes and durations are recorded side by side and never divided.
//! - **Nothing here is compared with any earlier section of `kernel/RESULTS.md`.** This fixture has
//!   403 row groups where every earlier one had a single row group, and the confound is declared.
//! - The 145 MB **in-session control** is generated by this same binary in this same session, with
//!   the same `row_group_rows`, and it is the only thing the 5 GB memory figure may be compared
//!   with.

mod support;

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::{Duration, Instant};

use spatial_engine::fixture::{
    write_geoparquet_cancellable, AttributeMode, CrsMode, FixtureFacts, FixtureProgress,
    FixtureSpec, IdentityMode, LicenseMode,
};
use spatial_engine::identity::IdentityDeclaration;
use spatial_engine::{Bbox, CancelToken, Dataset, ViewportQuery};
use support::*;

// ---- Pre-registered, from SCALE-PASS-PREREGISTRATION.md §1a ------------------------------------

const FEATURES: usize = 3_300_000;
const AVG_VERTICES: usize = 100;
const HOLE_EVERY: usize = 7;
const SEED: u64 = 0x5EED_2056_0000_0005;
const CHUNK: usize = 8_192;
const ROW_GROUP_ROWS: usize = 8_192;

/// The in-session control (§6). Same binary, same session, same `row_group_rows` — the second point
/// the "flat with respect to file size" claim needs, since between-session comparison is forbidden.
const CONTROL_FEATURES: usize = 100_000;

// ---- Pre-registered predictions (§1b), asserted rather than recomputed --------------------------

const PREDICTED_RINGS: usize = 3_771_429;
const PREDICTED_ROW_GROUPS: usize = 403;
/// Exact, from the generator's grid: (⌊1817/2⌋+1)².
const QUARTER_ROWS: u64 = 826_281;
/// Exact: (⌊1817/8⌋+1)².
const SIXTY_FOURTH_ROWS: u64 = 51_984;
/// The generator's grid, restated. `⌈√3_300_000⌉` and its 40 m cell are locals inside
/// `fixture::parcel` and are not public, so these are duplicates — and a generator change would
/// move the viewports silently. The row-count assertions below are what catches that.
const GRID_COLS: usize = 1817;
const CELL_M: f64 = 40.0;

/// A viewport edge that lands **on a cell centre**, and the reason that matters.
///
/// A parcel's bbox always straddles its own centre, so an edge at a centre includes that column
/// unconditionally — the covering-bbox filter's answer is then pure arithmetic and cannot depend on
/// per-feature vertex jitter.
///
/// **This was a real defect, caught before the run.** The 1/64 edge was `1817/8 × 40 = +9085`,
/// which lands 15 m *into* cell 227 whose centre is at +20 m. Inclusion then needed a parcel's
/// leftward reach — `16.8 × jitter × −cos θ`, jitter ~ U[0.55, 1] — to be ≥ 15 m, which fails for
/// roughly 7 % of parcels. The registered "exact" 51 984 would have come back as 51 953, and the
/// preregistration says an exact-count mismatch stops the pass as an instrument failure. The
/// quarter's `1817/2 × 40 = +36340` happened to equal `908 × 40 + 20` and so was already robust —
/// by luck. This makes both deliberate.
fn viewport_edge(divisor: usize) -> f64 {
    let last_col = GRID_COLS / divisor; // integer division: the last column wholly inside
    last_col as f64 * CELL_M + CELL_M / 2.0
}

/// Columns included by [`viewport_edge`], squared — the exact row count.
fn viewport_rows(divisor: usize) -> u64 {
    let cols = (GRID_COLS / divisor + 1) as u64;
    cols * cols
}

/// **The computed viewports must equal the pre-registered numbers.**
///
/// Not #[ignore]d: it runs in the ordinary suite, costs nothing, and is what keeps the harness and
/// `SCALE-PASS-PREREGISTRATION.md` §1b from drifting apart. Without it the registered constants are
/// prose beside code that computes something else — which is exactly the defect the reviewer found
/// in the 1/64 edge.
#[test]
fn the_viewports_match_the_preregistered_row_counts() {
    assert_eq!(viewport_rows(2), QUARTER_ROWS, "the quarter viewport no longer matches §1b");
    assert_eq!(viewport_rows(8), SIXTY_FOURTH_ROWS, "the 1/64 viewport no longer matches §1b");
    // Both edges land on a cell centre, which is what makes the counts robust rather than lucky.
    for divisor in [2usize, 8] {
        let offset = viewport_edge(divisor);
        let cells = (offset - CELL_M / 2.0) / CELL_M;
        assert!(
            (cells - cells.round()).abs() < 1e-9,
            "the 1/{divisor} edge at +{offset} is not on a cell centre, so its row count depends on \n             per-feature vertex jitter"
        );
    }
}

// ---- Pre-registered sample counts (§6) ---------------------------------------------------------

const WHOLE_FILE_RUNS: usize = 5;
const VIEWPORT_RUNS: usize = 7;
const CANCEL_TRIALS: usize = 7;
/// Alternating ABBA pairs for the identity-scan A/B (each pair is two A and two B opens).
const AB_PAIRS: usize = 3;
/// Settle before the first measured phase. Matches the cold-open protocol's declared 120 s, so the
/// attended and unattended halves of this pass ask the machine for the same quiet.
const SETTLE_SECONDS: u64 = 120;

// ---- Pre-registered watchdog ceilings (§3) -----------------------------------------------------

const CEIL_GENERATE: Duration = Duration::from_secs(1800);
const CEIL_GENERATE_CONTROL: Duration = Duration::from_secs(300);
const CEIL_OPEN: Duration = Duration::from_secs(300);
const CEIL_WHOLE_FILE: Duration = Duration::from_secs(900);
const CEIL_VIEWPORT: Duration = Duration::from_secs(600);
const CEIL_CANCEL: Duration = Duration::from_secs(60);
const SILENCE_STREAM: Duration = Duration::from_secs(120);
const SILENCE_GENERATE: Duration = Duration::from_secs(60);

// ---- Pre-registered sampler cadences (§6) ------------------------------------------------------

const CADENCE_SHORT_MS: u64 = 50;
const CADENCE_LONG_MS: u64 = 250;

/// `docs/08`: cancellation acknowledged < 100 ms, **any operation**. No size exemption.
const CANCEL_BUDGET_MS: f64 = 100.0;

fn evidence_dir() -> PathBuf {
    let d = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("target/slice-evidence/scale-pass");
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn fixture_path() -> PathBuf {
    evidence_dir().join("parcels-5gb.parquet")
}

fn control_path() -> PathBuf {
    evidence_dir().join("parcels-control-145mb.parquet")
}

fn spec_5gb() -> FixtureSpec {
    FixtureSpec {
        features: FEATURES,
        avg_vertices: AVG_VERTICES,
        hole_every: HOLE_EVERY,
        seed: SEED,
        crs_mode: CrsMode::DeclaredLv95,
        with_covering_bbox: true,
        chunk: CHUNK,
        row_group_rows: ROW_GROUP_ROWS,
        identity: IdentityMode::NativeUnique,
        attributes: AttributeMode::None,
        // Determinism-critical: a source-declared license needs no `--license-at`, and an
        // operator-declared instant is a semantic input inside ADR-017 §12's determinism surface.
        license: LicenseMode::DeclaredBySource,
    }
}

fn spec_control() -> FixtureSpec {
    FixtureSpec { features: CONTROL_FEATURES, ..spec_5gb() }
}

/// Progress that feeds the watchdog's silence clock and counts chunks.
struct GenProgress<'a> {
    dog: &'a Watchdog,
    chunks: AtomicUsize,
}

impl FixtureProgress for GenProgress<'_> {
    fn chunk_written(&self, _i: usize, written: usize, total: usize, bytes: u64) {
        self.dog.beat();
        let n = self.chunks.fetch_add(1, Ordering::Relaxed);
        if n % 50 == 0 {
            println!("  [generate] {written}/{total} features, {bytes} B");
        }
    }
}

/// SHA-256 of a file, streamed. **Never called at cold time** — see the preregistration §4a.
fn sha256_file(path: &Path) -> std::io::Result<String> {
    use std::io::Read as _;
    let mut f = std::fs::File::open(path)?;
    let mut buf = vec![0u8; 8 << 20];
    let mut all: Vec<u8> = Vec::new();
    // Hashed incrementally would be better; `canonical::sha256_hex` takes a slice, so this reads in
    // blocks and accumulates. At 5 GB that is 5 GB resident for the duration of the hash — which is
    // why this is called in its own phase, never inside a memory measurement.
    loop {
        let n = f.read(&mut buf)?;
        if n == 0 {
            break;
        }
        all.extend_from_slice(&buf[..n]);
    }
    Ok(spatial_renderer::canonical::sha256_hex(&all))
}

/// One streaming run: time to first batch, total time, rows, batches.
struct StreamRun {
    first_batch_ms: f64,
    total_ms: f64,
    rows: u64,
    batches: usize,
    /// The engine's own report of how the query was planned. Recorded rather than inferred: this
    /// pass is framed throughout as "ScanOnly, no index", and  exists so that is a
    /// fact in the artifact instead of an assumption in the prose.
    filter_plan: String,
}

fn stream_once(ds: &Dataset, q: &ViewportQuery, dog: &Watchdog, cancel: CancelToken) -> StreamRun {
    let t0 = Instant::now();
    let mut stream = ds.stream_with_cancel(q, cancel).expect("stream opens");
    let mut payload = Vec::new();
    let mut first: Option<f64> = None;
    let mut rows = 0u64;
    let mut batches = 0usize;

    while let Some(info) = stream.next_into(&mut payload) {
        let info = info.expect("batch");
        if first.is_none() {
            first = Some(t0.elapsed().as_secs_f64() * 1000.0);
        }
        rows += info.rows as u64;
        batches += 1;
        payload.clear();
        dog.beat();
    }
    StreamRun {
        first_batch_ms: first.unwrap_or(f64::NAN),
        total_ms: t0.elapsed().as_secs_f64() * 1000.0,
        rows,
        batches,
        filter_plan: format!("{:?}", stream.filter_plan()),
    }
}

#[ignore = "measurement harness: ~5 GB of disk, tens of minutes, release-only"]
#[test]
fn measure_the_five_gigabyte_scale_pass() {
    refuse_debug("the 5 GB scale pass");

    let dir = evidence_dir();
    let mut json = String::from("{\n");
    let mut canaries: Vec<Canary> = Vec::new();

    let hardware = json_escape(&hardware_profile());
    let media = json_escape(&media_type());
    println!("hardware: {hardware}");
    println!("media:    {media}");
    json.push_str(&format!("  \"hardware\": \"{hardware}\",\n  \"media_type\": \"{media}\",\n"));
    json.push_str(&format!(
        "  \"preregistration\": \"kernel/SCALE-PASS-PREREGISTRATION.md\",\n  \"cadence_short_ms\": {CADENCE_SHORT_MS},\n  \"cadence_long_ms\": {CADENCE_LONG_MS},\n"
    ));

    // **A settle before the first canary, and the reason is attempt 1.**
    //
    // Attempt 1 was invalidated by its own declared canary invalidator: spread 0.1194 against a
    // declared 0.10. The outlier was the START point (114.2 ms) taken seconds after a 12-minute
    // clean release build and a 328-test correctness gate — the five points that actually bracket
    // measured phases spanned 9.4 %, inside the bound. The machine had not settled, and the
    // instrument recorded that faithfully.
    //
    // The pre-settle reading is taken and **recorded**, but is deliberately NOT one of the points
    // the spread invalidator is computed over. That exclusion is narrow and is stated rather than
    // assumed: the invalidator asks whether the machine moved *while numbers were being taken*, and
    // no number is taken before the settle. A point that brackets no measurement cannot witness
    // drift in one. Recording it anyway is what stops this being a way to dodge the invalidator —
    // the artifact shows how far the machine was from settled, in the same units.
    let pre_settle = Canary::take("pre-settle");
    println!("  settling for {} s before the first measured phase...", SETTLE_SECONDS);
    std::thread::sleep(Duration::from_secs(SETTLE_SECONDS));
    canaries.push(Canary::take("start"));
    json.push_str(&format!("  \"pre_settle_canary\": {}, \"settle_seconds\": {SETTLE_SECONDS},
", pre_settle.json()));

    // ---- Phase 1: the fixtures -----------------------------------------------------------------
    let free_before = require_disk("generate");
    json.push_str(&format!("  \"free_bytes_before\": {free_before},\n"));

    let (facts, gen_ms) = generate(&fixture_path(), &spec_5gb(), CEIL_GENERATE, "generate-5gb");
    let (control_facts, control_gen_ms) = generate(
        &control_path(),
        &spec_control(),
        CEIL_GENERATE_CONTROL,
        "generate-control",
    );

    // **Predictions asserted, not recomputed.** A mismatch here is an instrument failure and stops
    // the pass; it is not a machine fact to be reported as a result.
    assert_eq!(facts.features, FEATURES, "the generator wrote a different feature count");
    assert_eq!(facts.rings, PREDICTED_RINGS, "ring count differs from the pre-registered prediction");
    assert!(
        (4.0e9..=6.5e9).contains(&(facts.bytes as f64)),
        "fixture is {} B, outside the pre-registered 4.0–6.5 GB regeneration band",
        facts.bytes
    );

    let fixture_sha = sha256_file(&fixture_path()).expect("hash the fixture");
    println!("fixture sha256: {fixture_sha}");

    json.push_str(&format!(
        "  \"fixture\": {{\"path\": \"parcels-5gb.parquet\", \"sha256\": \"{fixture_sha}\", \
         \"features\": {}, \"vertices\": {}, \"rings\": {}, \"bytes\": {}, \
         \"min_vertices\": {}, \"max_vertices\": {}, \"coord_bits_xor\": \"{:#018x}\", \
         \"extent\": [{:.3}, {:.3}, {:.3}, {:.3}], \"wall_ms\": {:.1}, \
         \"predicted_vertices\": 345414000, \"predicted_rings\": {PREDICTED_RINGS}, \
         \"predicted_bytes\": 5009600000, \"predicted_row_groups\": {PREDICTED_ROW_GROUPS}}},\n",
        facts.features, facts.vertices, facts.rings, facts.bytes,
        facts.min_vertices_per_feature, facts.max_vertices_per_feature, facts.coord_bits_xor,
        facts.extent[0], facts.extent[1], facts.extent[2], facts.extent[3], gen_ms
    ));
    json.push_str(&format!(
        "  \"control_fixture\": {{\"features\": {}, \"vertices\": {}, \"bytes\": {}, \"wall_ms\": {:.1}}},\n",
        control_facts.features, control_facts.vertices, control_facts.bytes, control_gen_ms
    ));
    canaries.push(Canary::take("after-generate"));

    // ---- Phase 2: warm open, and the identity scan isolated by A/B ------------------------------
    require_disk("open");
    let (full_opens, prelude_opens, scan_a_first, scan_b_first) = open_ab(&fixture_path());
    let full_p50 = pct(&sorted(&full_opens), 0.5);
    let prelude_p50 = pct(&sorted(&prelude_opens), 0.5);
    println!(
        "open: full p50 {full_p50:.1} ms | prelude-only p50 {prelude_p50:.1} ms | scan estimate \
         {scan_a_first:.1} ms (A-first) / {scan_b_first:.1} ms (B-first)"
    );
    json.push_str(&format!(
        "  \"warm_open\": {{\"full\": {}, \"prelude_only\": {}, \
         \"identity_scan_ms_a_first\": {scan_a_first:.3}, \
         \"identity_scan_ms_b_first\": {scan_b_first:.3}, \
         \"basis\": \"A/B on two product paths (skip_uniqueness_check true/false), same session, \
         same binary, one discarded warm-up open, {AB_PAIRS} alternating ABBA pairs. The two order \
         estimates are reported separately and NOT averaged: if they disagree, the order effect is \
         the finding.\"}},\n",
        summarize("open, full (with uniqueness scan)", &full_opens),
        summarize("open, prelude only (scan skipped)", &prelude_opens),
    ));
    canaries.push(Canary::take("after-open"));

    // ---- Phase 3: streaming ---------------------------------------------------------------------
    require_disk("stream");
    let ds = Dataset::open(fixture_path()).expect("open the 5 GB fixture");

    let whole = ViewportQuery { bbox: None, bbox_crs: None, limit: None };
    let (whole_first, whole_total, whole_rows, whole_batches, whole_mem, whole_plan) =
        stream_phase(&ds, &whole, WHOLE_FILE_RUNS, CEIL_WHOLE_FILE, "whole-file");
    assert_eq!(whole_rows, FEATURES as u64, "the whole-file stream did not return every row");

    let e_lo = spatial_engine::fixture::E_LO;
    let n_lo = spatial_engine::fixture::N_LO;
    // **`bbox_crs` names the dataset's own CRS rather than being `None`.** With `None` the engine's
    // CRS-admission branch is never entered, so a row-count mismatch could not distinguish a filter
    // fault from an admission fault — and the admission fault is one of the three things §1b claims
    // these exact counts would reveal. Naming it costs nothing and exercises the branch.
    let crs = ds.crs().identifier().to_string();
    let viewport = |divisor: usize| ViewportQuery {
        bbox: Some(Bbox {
            xmin: e_lo,
            ymin: n_lo,
            xmax: e_lo + viewport_edge(divisor),
            ymax: n_lo + viewport_edge(divisor),
        }),
        bbox_crs: Some(crs.clone()),
        limit: None,
    };

    let quarter = viewport(2);
    let (q_first, q_total, q_rows, q_batches, _, q_plan) =
        stream_phase(&ds, &quarter, VIEWPORT_RUNS, CEIL_VIEWPORT, "quarter");

    let sixty_fourth = viewport(8);
    let (s_first, s_total, s_rows, s_batches, _, s_plan) =
        stream_phase(&ds, &sixty_fourth, VIEWPORT_RUNS, CEIL_VIEWPORT, "sixty-fourth");

    // **The strongest instrument check in the pass, and it is ASSERTED.**
    //
    // Both edges land on a cell centre (see `viewport_edge`), so a parcel's bbox always straddles
    // the boundary column and the covering-bbox filter's answer is pure arithmetic over the grid —
    // independent of per-feature vertex jitter. A mismatch therefore means the filter, the
    // generator or the CRS admission is wrong, not that the machine drifted, and the
    // preregistration §7 says that stops the pass rather than being reported as a result.
    assert_eq!(
        q_rows,
        viewport_rows(2),
        "the quarter viewport returned {q_rows} rows, not the exact {} the grid predicts",
        viewport_rows(2)
    );
    assert_eq!(
        s_rows,
        viewport_rows(8),
        "the 1/64 viewport returned {s_rows} rows, not the exact {} the grid predicts",
        viewport_rows(8)
    );

    json.push_str(&format!(
        "  \"streaming\": {{\"filter_plans\": {{\"whole_file\": {whole_plan:?}, \"quarter\": {q_plan:?}, \"sixty_fourth\": {s_plan:?}}}, \
         \"whole_file\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {whole_rows}, \"batches\": {whole_batches}}},\
         \"quarter\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {q_rows}, \"predicted_rows\": {}, \"batches\": {q_batches}}},\
         \"sixty_fourth\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {s_rows}, \"predicted_rows\": {}, \"batches\": {s_batches}}}}},\n",
        summarize("whole-file first batch", &whole_first),
        summarize("whole-file total", &whole_total),
        summarize("quarter first batch", &q_first),
        summarize("quarter total", &q_total),
        viewport_rows(2),
        summarize("1/64 first batch", &s_first),
        summarize("1/64 total", &s_total),
        viewport_rows(8),
    ));
    canaries.push(Canary::take("after-streaming"));

    // ---- Phase 4: cancellation mid-stream at scale ------------------------------------------------
    //
    // **Before the memory control, and that ordering is the fix for a real defect.** The control
    // must not be sampled while the 5 GB `Dataset` — its pool, its DuckDB connection and its buffer
    // manager — is still resident, or both points of the "flat with respect to file size" claim
    // would be dominated by the same 5 GB residue and would look flat for a reason that has nothing
    // to do with file size. So every phase that needs `ds` runs first, and `ds` is dropped before
    // the control is opened.
    require_disk("cancel");
    let cancel = cancel_phase(&ds, &whole);
    let cs = sorted(&cancel.ack_ms);
    let cancel_max = cs.last().copied().unwrap_or(f64::NAN);
    println!(
        "cancellation: n={} p50 {:.2} ms p95 {:.2} ms max {:.2} ms (budget {CANCEL_BUDGET_MS} ms) | batches after cancel max {}",
        cs.len(),
        pct(&cs, 0.5),
        pct(&cs, 0.95),
        cancel_max,
        cancel.batches_after_cancel.iter().copied().max().unwrap_or(0)
    );
    json.push_str(&format!(
        "  \"cancellation_mid_stream\": {{\"acknowledgement\": {}, \"drain_to_terminal\": {}, \
         \"budget_ms\": {CANCEL_BUDGET_MS}, \"max_ack_ms\": {cancel_max:.3}, \
         \"batches_after_cancel\": {}, \
         \"definitions\": \"acknowledgement = cancel() until the FIRST next_into returns after it \
         (what docs/08's budget is about); drain_to_terminal = cancel() until the stream is over, \
         which includes IPC-encoding the batches already queued when the cancel arrived. The two \
         are reported separately because the second is dominated by work produced BEFORE the \
         cancel and is not the property the budget names.\"}},\n",
        summarize("cancel acknowledgement", &cancel.ack_ms),
        summarize("cancel drain to terminal", &cancel.drain_ms),
        json_usizes(&cancel.batches_after_cancel),
    ));
    canaries.push(Canary::take("after-cancel"));

    // ---- Phase 5: the memory row, with its in-session control ---------------------------------------
    //
    // `ds` is dropped here, before the control is opened, so the control's private-commit samples
    // are not measuring the 5 GB dataset's residue. A baseline is taken immediately after the drop
    // and recorded beside both peaks, because the allocator does not return everything to the OS
    // and pretending it does would overstate the control.
    let peak_5gb = whole_mem.iter().copied().max().unwrap_or(0);
    drop(ds);
    std::thread::sleep(Duration::from_secs(2));
    let baseline_after_drop = procmem::sample().map(|c| c.private_usage).unwrap_or(0);

    let control_ds = Dataset::open(control_path()).expect("open the control fixture");
    let (_, _, _, _, control_mem, _) =
        stream_phase(&control_ds, &whole, 1, CEIL_WHOLE_FILE, "control-whole-file");
    let peak_control = control_mem.iter().copied().max().unwrap_or(0);
    drop(control_ds);

    println!(
        "private commit: 5 GB peak {peak_5gb} B | baseline after drop {baseline_after_drop} B | control peak {peak_control} B"
    );
    json.push_str(&format!(
        "  \"memory\": {{\"peak_private_commit_5gb\": {peak_5gb}, \
         \"baseline_after_dropping_5gb_dataset\": {baseline_after_drop}, \
         \"peak_private_commit_control\": {peak_control}, \
         \"declared_composed_bound_bytes\": 83886080, \
         \"caveat\": \"process private commit is NOT the bounded quantity. DuckDB's own streaming \
         buffer sits outside every declared bound by design, and in publish an ORDER BY sort of \
         ~7 GB does too. The bounded claim is the data-plane window. These two peaks are the two \
         points the flatness statement needs -- same session, same binary, same row_group_rows -- \
         and the baseline between them is recorded because the allocator does not return \
         everything to the OS when the 5 GB dataset is dropped.\"}},\n"
    ));
    canaries.push(Canary::take("after-memory"));

    // ---- Close out -------------------------------------------------------------------------------
    let (spread, canary_ok) = canary_spread(&canaries);
    let free_after = free_bytes_on_c().unwrap_or(0);
    let points: Vec<String> = canaries.iter().map(Canary::json).collect();
    json.push_str(&format!(
        "  \"canary\": {{\"points\": [{}], \"long_min_spread\": {spread:.4}, \"declared_max_spread\": {CANARY_MAX_SPREAD}, \"within_declared\": {canary_ok}}},\n",
        points.join(", ")
    ));
    json.push_str(&format!("  \"free_bytes_after\": {free_after},\n"));
    // **A provenance note goes into the artifact, so it must name things that exist.** An earlier
    // draft pointed at `kernel/scripts/run-scale-publish.mjs`, which was never written — and this
    // string is what a reader of RESULTS.md consults to find out how the numbers were taken.
    json.push_str("  \"note\": \"Publish, determinism and strict-reader phases are `measure_publish_at_five_gigabytes` in kernel/tests/scale_pass.rs, run from these same frozen binaries. The cold-open row is kernel/scripts/cold-open.ps1 and runs last, after three operator-assisted restarts.\"\n}\n");

    let artifact = dir.join("scale-pass.json");
    std::fs::write(&artifact, &json).expect("write the evidence artifact");
    println!("artifact: {}", artifact.display());

    // **Asserted last, so the artifact exists either way.** A phase whose canary moved is recorded
    // with its invalidator named rather than silently dropped.
    assert!(
        canary_ok,
        "canary spread {spread:.4} exceeds the declared {CANARY_MAX_SPREAD} — the machine moved \
         underneath these numbers and the run is invalidated"
    );
}

/// Generate one fixture under a declared ceiling, returning its facts and wall time.
fn generate(
    path: &Path,
    spec: &FixtureSpec,
    ceiling: Duration,
    phase: &'static str,
) -> (FixtureFacts, f64) {
    // **Refused rather than reused, and the reason is not tidiness.** `FixtureFacts` are what the
    // *writer* measured while writing — vertices, rings, the coordinate XOR, the extent — and none
    // of them can be recovered from a finished file without re-reading and re-deriving them, which
    // would be a second implementation of the generator's own accounting. A reuse path would have
    // to fabricate the facts this pass records beside its predictions.
    assert!(
        !path.exists(),
        "{} already exists. This pass generates once and records the facts from that generation. \
         Remove the file to re-run the phase — deliberately manual, because it is 5 GB.",
        path.display()
    );

    let cancel = CancelToken::new();
    let dog = Watchdog::start(phase, ceiling, Some(SILENCE_GENERATE), cancel.clone());
    let progress = GenProgress { dog: &dog, chunks: AtomicUsize::new(0) };

    let t0 = Instant::now();
    let facts = write_geoparquet_cancellable(path, spec, &cancel, Some(&progress))
        .expect("fixture generation");
    let ms = t0.elapsed().as_secs_f64() * 1000.0;
    let fired = dog.finish();
    assert!(!fired, "the {phase} watchdog fired; this phase is unmeasured and is not re-run");

    // Wall time and bytes side by side, deliberately not divided.
    println!("[{phase}] {} features, {} B, {ms:.0} ms", facts.features, facts.bytes);
    (facts, ms)
}

/// Open the dataset on two product paths, so the identity scan is a **difference** rather than an
/// inference. Returns (full open ms, prelude-only ms, per-order estimates).
///
/// ## Why alternating pairs and a discarded warm-up, rather than one A then one B
///
/// The first draft ran A once then B once and called `A − B` the scan. Three things made that
/// unsound, and all three push the estimate the same way:
///
/// - **A was the first `Dataset::open` in the process**, so DuckDB's process-level initialization
///   and first-connection cost landed entirely in A and therefore entirely in the "scan".
/// - **One ordering, n = 1** — no way to see an order effect, let alone subtract it.
/// - A reads the footer *plus the `id` column*; B reads only the footer. Whatever first-touch cost
///   remains after the file is cached is asymmetric by construction and was attributed to the scan.
///
/// So: one discarded warm-up open, then `AB_PAIRS` alternating **ABBA** pairs. Both order estimates
/// are reported. **If they disagree, the order effect is the finding** — not something to average
/// away.
fn open_ab(path: &Path) -> (Vec<f64>, Vec<f64>, f64, f64) {
    let cancel = CancelToken::new();
    let dog = Watchdog::start("open-ab", CEIL_OPEN, None, cancel);

    let open_full = |p: &Path| -> f64 {
        let t = Instant::now();
        let ds = Dataset::open(p).expect("open with the uniqueness scan");
        let ms = t.elapsed().as_secs_f64() * 1000.0;
        drop(ds);
        ms
    };
    let open_prelude = |p: &Path| -> f64 {
        let mut d = IdentityDeclaration::new("id", "scale-pass", "2026-08-07T00:00:00Z");
        d.skip_uniqueness_check = true;
        let t = Instant::now();
        let ds = Dataset::open_with_declared_identity(p, d, &CancelToken::new())
            .expect("open with the scan skipped");
        let ms = t.elapsed().as_secs_f64() * 1000.0;
        drop(ds);
        ms
    };

    // Discarded: this pays for DuckDB's first instance in the process, and nothing else should.
    let warmup = open_full(path);
    println!("  [open-ab] warm-up (discarded): {warmup:.1} ms");

    let mut full = Vec::with_capacity(AB_PAIRS * 2);
    let mut prelude = Vec::with_capacity(AB_PAIRS * 2);
    let mut a_first_deltas = Vec::with_capacity(AB_PAIRS);
    let mut b_first_deltas = Vec::with_capacity(AB_PAIRS);

    for i in 0..AB_PAIRS {
        // ABBA: A,B then B,A. Each pair contributes one estimate in each order.
        let a1 = open_full(path);
        let b1 = open_prelude(path);
        a_first_deltas.push(a1 - b1);

        let b2 = open_prelude(path);
        let a2 = open_full(path);
        b_first_deltas.push(a2 - b2);

        full.push(a1);
        full.push(a2);
        prelude.push(b1);
        prelude.push(b2);
        println!("  [open-ab] pair {}/{AB_PAIRS}: A {a1:.1} B {b1:.1} | B {b2:.1} A {a2:.1}", i + 1);
    }

    assert!(!dog.finish(), "the open watchdog fired; this phase is unmeasured");
    let a_first = pct(&sorted(&a_first_deltas), 0.5);
    let b_first = pct(&sorted(&b_first_deltas), 0.5);
    (full, prelude, a_first, b_first)
}

/// n runs of one query, each under its own declared ceiling, with private commit sampled throughout.
///
/// **One watchdog per run, not per phase.** The preregistration declares the whole-file and
/// viewport ceilings *per run*; a single watchdog spanning 5 or 7 runs would make the effective
/// per-run ceiling 5× or 7× tighter than registered, in the direction of a spurious abort.
///
/// **The token the watchdog fires is the token the stream uses.** An earlier draft constructed one
/// token for the watchdog and a different one inside the stream, so a fired watchdog reached
/// nothing, the phase could not return inside the grace, and the process aborted — losing the whole
/// run rather than marking one row unmeasured.
#[allow(clippy::type_complexity)]
fn stream_phase(
    ds: &Dataset,
    q: &ViewportQuery,
    runs: usize,
    ceiling: Duration,
    phase: &'static str,
) -> (Vec<f64>, Vec<f64>, u64, usize, Vec<usize>, String) {
    let sampler = MemorySampler::start(CADENCE_LONG_MS);
    let mut first = Vec::with_capacity(runs);
    let mut total = Vec::with_capacity(runs);
    let (mut rows, mut batches) = (0u64, 0usize);
    let mut plan = String::from("(unrecorded)");

    for i in 0..runs {
        let cancel = CancelToken::new();
        let dog = Watchdog::start(phase, ceiling, Some(SILENCE_STREAM), cancel.clone());
        let r = stream_once(ds, q, &dog, cancel);
        let fired = dog.finish();
        assert!(!fired, "the {phase} watchdog fired on run {}; this phase is unmeasured", i + 1);

        println!(
            "  [{phase}] run {}/{runs}: first batch {:.1} ms, total {:.1} ms, {} rows, {} batches",
            i + 1,
            r.first_batch_ms,
            r.total_ms,
            r.rows,
            r.batches
        );
        first.push(r.first_batch_ms);
        total.push(r.total_ms);
        // **Every run's row count is checked against the first**, so an assertion on `rows` is an
        // assertion about the phase rather than about whichever run happened to be last.
        if i == 0 {
            rows = r.rows;
            batches = r.batches;
            plan = r.filter_plan;
        } else {
            assert_eq!(r.rows, rows, "{phase} run {} returned a different row count", i + 1);
        }
    }

    let samples = sampler.finish();
    (first, total, rows, batches, samples, plan)
}

/// What one cancellation trial measured.
struct CancelPhase {
    /// `cancel()` → the first `next_into` that returns after it. **This is what `docs/08`'s budget
    /// is about**: how quickly the operation acknowledges.
    ack_ms: Vec<f64>,
    /// `cancel()` → the stream is over. Includes IPC-encoding whatever was already queued when the
    /// cancel arrived, so it is dominated by work produced *before* the cancel.
    drain_ms: Vec<f64>,
    /// The engine's own count, the same H2 property every prior cancellation row carries.
    batches_after_cancel: Vec<usize>,
}

/// Cancellation mid-stream, producer-observed, in one process so both observations share a clock.
///
/// ## Two numbers, because the first draft measured the wrong one
///
/// It timed from `cancel()` until the drain loop ended. With `MAX_QUEUED_BATCHES = 2` plus a
/// producer blocked in `send`, up to **three already-generated batches** are in flight when the
/// cancel lands, and `next_into` IPC-encodes each one before the terminal can arrive. So that
/// interval is `3 × (recv + ~1 MiB encode)` — a real quantity, but not "acknowledged", and it would
/// have gone into `RESULTS.md` against a budget it does not describe.
fn cancel_phase(ds: &Dataset, q: &ViewportQuery) -> CancelPhase {
    let mut out = CancelPhase {
        ack_ms: Vec::with_capacity(CANCEL_TRIALS),
        drain_ms: Vec::with_capacity(CANCEL_TRIALS),
        batches_after_cancel: Vec::with_capacity(CANCEL_TRIALS),
    };

    for trial in 0..CANCEL_TRIALS {
        let cancel = CancelToken::new();
        let dog = Watchdog::start("cancel", CEIL_CANCEL, None, cancel.clone());
        let sampler = MemorySampler::start(CADENCE_SHORT_MS);

        let mut stream = ds.stream_with_cancel(q, cancel.clone()).expect("stream opens");
        let mut payload = Vec::new();

        // Reach steady state first — a cancel before the first batch measures a different thing and
        // has its own coverage in the ordinary suite.
        let mut seen = 0;
        while seen < 2 {
            match stream.next_into(&mut payload) {
                Some(Ok(_)) => {
                    seen += 1;
                    payload.clear();
                }
                Some(Err(e)) => panic!("stream failed before cancellation: {e}"),
                None => break,
            }
        }

        let t = Instant::now();
        cancel.cancel();

        // **Acknowledgement**: the very next return, whatever it is.
        let _ = stream.next_into(&mut payload);
        let ack_ms = t.elapsed().as_secs_f64() * 1000.0;
        payload.clear();

        // **Drain**: everything already in flight, to the terminal.
        while let Some(r) = stream.next_into(&mut payload) {
            payload.clear();
            if r.is_err() {
                break;
            }
        }
        let drain_ms = t.elapsed().as_secs_f64() * 1000.0;
        let after = stream.stats().batches_after_cancel.load(std::sync::atomic::Ordering::SeqCst) as usize;

        println!(
            "  [cancel] trial {}/{CANCEL_TRIALS}: ack {ack_ms:.2} ms, drain {drain_ms:.2} ms, {after} batches after cancel",
            trial + 1
        );
        out.ack_ms.push(ack_ms);
        out.drain_ms.push(drain_ms);
        out.batches_after_cancel.push(after);

        let _ = sampler.finish();
        assert!(!dog.finish(), "the cancel watchdog fired on trial {trial}");
    }
    out
}

// ================================================================================================
// Phases 6-9: publish at scale, determinism, and strict-reader verification
// ================================================================================================

/// **The class-3 boundary's first real workout**, plus determinism and verification.
///
/// A separate `#[ignore]`d test from the streaming phases, for one reason: it needs the fixture the
/// first test generates, and splitting them lets the operator re-run the publish half without
/// regenerating 5 GB. It refuses to run if the fixture is absent rather than generating one, so the
/// two halves can never disagree about which file they measured.
///
/// ## Why the CLI, and why not for cancellation
///
/// Publishes A and B go through `publish-bundle` — the sanctioned `--approve` path, exercising the
/// composition root an operator actually runs. Cancellation does **not**: a threshold asserted
/// across a process boundary measures scheduling, not the property, so cancellation cells belong
/// in-process where both observations share one clock. They are covered by the ordinary suite's
/// boundary tests and by the mid-stream cells above; a *publish* cancellation cell at 5 GB is
/// registered in the preregistration and is driven separately, because aiming at a phase requires
/// the in-process progress observer.
///
/// ## The grant is self-minted, and that is disclosed rather than hidden
///
/// The human's F-5 ruling binds a future **exposure surface**: the requester must never mint the
/// grant. A harness invoked from the operator's own shell against developer/test tooling is the
/// operator's hand, not a requester. Every publish nonetheless passes `--grant-destination`, the
/// only non-tautological part of a self-minted grant, so at least one scope member is checked
/// against a resolved fact.
#[ignore = "measurement harness: publishes ~5.7 GB twice, release-only; needs the fixture from the streaming phase"]
#[test]
fn measure_publish_at_five_gigabytes() {
    refuse_debug("the 5 GB publish pass");
    let dir = evidence_dir();
    let fixture = fixture_path();
    assert!(
        fixture.exists(),
        "the 5 GB fixture is absent at {}. Run `measure_the_five_gigabyte_scale_pass` first; this \
         phase deliberately does not generate one, so the two halves cannot measure different files.",
        fixture.display()
    );

    require_disk("publish");
    let mut canaries = vec![Canary::take("publish-start")];
    let mut json = String::from("{\n");

    // The audit log for this run only — never the operator's real one. Preregistration section 5c.
    let audit_dir = dir.join("audit");
    let _ = std::fs::remove_dir_all(&audit_dir);
    std::fs::create_dir_all(&audit_dir).unwrap();
    let audit_log = audit_dir.join("publish.jsonl");
    assert!(!audit_log.exists(), "the audit log must start absent for the record-count assertions");

    // A destination that cannot trip F-3's bare-word credential needles. Checked before the run,
    // because a destination containing `secret`/`password`/`apikey`/`credential` refuses the
    // publish with NO audit record at all, which would look like a publish failure.
    let bundle_dir = dir.join("bundles");
    std::fs::create_dir_all(&bundle_dir).unwrap();
    let dest_lower = bundle_dir.to_string_lossy().to_ascii_lowercase();
    for needle in ["credential", "password", "passwd", "secret", "api_key", "apikey"] {
        assert!(
            !dest_lower.contains(needle),
            "the bundle destination contains `{needle}`, which the audit record's docs/09 scan \
             treats as a credential — the publish would refuse with no record written"
        );
    }

    let style_path = dir.join("scale-style.json");
    std::fs::write(&style_path, SCALE_STYLE).unwrap();
    let viewer_dir = dir.join("viewer");
    std::fs::create_dir_all(&viewer_dir).unwrap();
    std::fs::write(viewer_dir.join("index.html"), b"<!doctype html><title>scale</title>").unwrap();
    std::fs::write(viewer_dir.join("NOTICE.txt"), b"stub notice\n").unwrap();

    // ---- Publish A -------------------------------------------------------------------------------
    let a = bundle_dir.join("bundle-a");
    let (a_ok, a_ms, a_out) = publish_via_cli(&fixture, &style_path, &viewer_dir, &a, &audit_log);
    assert!(a_ok, "publish A failed:\n{a_out}");
    println!("[publish A] {a_ms:.0} ms");
    canaries.push(Canary::take("after-publish-a"));

    // ---- Publish B, to a different destination ----------------------------------------------------
    //
    // A different `--out`, because re-publish over an existing destination is a typed refusal — and
    // that is a *bonus*: ADR-017 section 13 forbids any local path in a bundle, so two different
    // destinations must still produce a byte-identical manifest. A stronger determinism check than
    // one destination could give.
    require_disk("publish-b");
    let b = bundle_dir.join("bundle-b");
    let (b_ok, b_ms, b_out) = publish_via_cli(&fixture, &style_path, &viewer_dir, &b, &audit_log);
    assert!(b_ok, "publish B failed:\n{b_out}");
    println!("[publish B] {b_ms:.0} ms");
    canaries.push(Canary::take("after-publish-b"));

    // ---- Determinism -------------------------------------------------------------------------------
    let manifest_a = sha256_file(&a.join("manifest.json")).unwrap();
    let manifest_b = sha256_file(&b.join("manifest.json")).unwrap();
    let manifests_identical = manifest_a == manifest_b;

    let (partitions_compared, partitions_identical, first_difference) = compare_partitions(&a, &b);
    println!(
        "determinism: manifests {} | {partitions_compared} partitions compared, identical={partitions_identical}",
        if manifests_identical { "identical" } else { "DIFFER" }
    );

    json.push_str(&format!(
        "  \"publish\": {{\"a_wall_ms\": {a_ms:.1}, \"b_wall_ms\": {b_ms:.1}, \
         \"manifest_sha256_a\": \"{manifest_a}\", \"manifest_sha256_b\": \"{manifest_b}\", \
         \"manifests_identical\": {manifests_identical}, \
         \"partitions_compared\": {partitions_compared}, \
         \"partitions_identical\": {partitions_identical}, \
         \"first_difference\": {:?}}},\n",
        first_difference.as_deref().unwrap_or("")
    ));

    // ---- Strict-reader verification ------------------------------------------------------------------
    let (v_ok, v_ms, v_summary) = verify_bundle(&a);
    println!("[verify] bundle A: ok={v_ok} in {v_ms:.0} ms");
    json.push_str(&format!(
        "  \"strict_reader\": {{\"verified\": {v_ok}, \"wall_ms\": {v_ms:.1}, \"summary\": {v_summary}}},\n"
    ));

    // ---- The audit record ------------------------------------------------------------------------------
    let audit_text = std::fs::read_to_string(&audit_log).expect("the audit log exists");
    let lines: Vec<&str> = audit_text.lines().filter(|l| !l.trim().is_empty()).collect();
    let mut intents = 0usize;
    let mut outcomes = 0usize;
    let mut manifest_hashes: Vec<String> = Vec::new();
    for l in &lines {
        let v: serde_json::Value = serde_json::from_str(l).expect("every audit line parses");
        assert_eq!(v["schema"], "spatial-audit/1", "unexpected audit schema");
        match v["phase"].as_str() {
            Some("intent") => intents += 1,
            Some("outcome") => {
                outcomes += 1;
                if let Some(h) = v["manifest_hash"].as_str() {
                    manifest_hashes.push(h.to_string());
                }
            }
            other => panic!("unexpected audit phase {other:?}"),
        }
    }
    println!("[audit] {} lines, {intents} intent, {outcomes} outcome", lines.len());
    assert_eq!(intents, outcomes, "every attempt must have both records");
    assert_eq!(intents, 2, "two publishes reached the gate");
    assert_eq!(manifest_hashes.len(), 2, "both successes record a manifest hash");
    assert_eq!(
        manifest_hashes[0], manifest_hashes[1],
        "the audit's two manifest hashes differ, so determinism fails at the record level"
    );
    assert_eq!(
        manifest_hashes[0], manifest_a,
        "the audit's manifest hash disagrees with the file on disk"
    );

    json.push_str(&format!(
        "  \"audit\": {{\"lines\": {}, \"intents\": {intents}, \"outcomes\": {outcomes}, \
         \"manifest_hash_matches_disk\": true, \
         \"log\": \"target/slice-evidence/scale-pass/audit/publish.jsonl\"}},\n",
        lines.len()
    ));

    let (spread, canary_ok) = canary_spread(&canaries);
    let points: Vec<String> = canaries.iter().map(Canary::json).collect();
    json.push_str(&format!(
        "  \"canary\": {{\"points\": [{}], \"long_min_spread\": {spread:.4}, \"within_declared\": {canary_ok}}}\n}}\n",
        points.join(", ")
    ));
    std::fs::write(dir.join("scale-publish.json"), &json).unwrap();

    // Asserted after the artifact is written, so a failure is still evidenced.
    assert!(manifests_identical, "ADR-017 determinism FAILED at 5 GB: the two manifests differ");
    assert!(partitions_identical, "partitions differ between two publishes of one request");
    assert!(v_ok, "the strict reader refused the bundle this pass published");
    assert!(canary_ok, "canary spread {spread:.4} exceeds the declared bound");
}

const SCALE_STYLE: &str = r##"{
  "style_version": 1,
  "layer": {
    "geometry": "polygon",
    "fill_color": {"literal": "#aa3333"},
    "fill_opacity": {"literal": 0.8},
    "outline_color": {"literal": "#202020"},
    "outline_width": {"literal": 1.0}
  }
}"##;

/// Run the real `publish-bundle`, through the sanctioned approval path.
fn publish_via_cli(
    data: &Path,
    style: &Path,
    viewer: &Path,
    out: &Path,
    audit_log: &Path,
) -> (bool, f64, String) {
    let exe = binary_beside_me("publish-bundle");
    let approve = out.file_name().unwrap().to_string_lossy().to_string();
    let grant_dir = out.parent().unwrap();

    let t = Instant::now();
    let output = std::process::Command::new(exe)
        .env("SPATIAL_IDE_AUDIT_LOG", audit_log)
        .args([
            "--data", data.to_str().unwrap(),
            "--style", style.to_str().unwrap(),
            "--viewer", viewer.to_str().unwrap(),
            "--out", out.to_str().unwrap(),
            "--approve", &approve,
            // The one part of a self-minted grant that is not a tautology.
            "--grant-destination", grant_dir.to_str().unwrap(),
            // The CLI pins a 5 GB source before the boundary runs; the 300 s default would be tight.
            "--grant-ttl", "900",
            "--viewer-program", "Spatial IDE bundle viewer",
            "--viewer-copyright", "Copyright (C) 2026 the Spatial IDE contributors",
            "--viewer-license", "AGPL-3.0-or-later",
            "--viewer-notice", "NOTICE.txt",
            "--corresponding-source-url", "https://example.invalid/spatial-ide",
        ])
        .output()
        .expect("run publish-bundle");
    let ms = t.elapsed().as_secs_f64() * 1000.0;
    let mut text = String::from_utf8_lossy(&output.stdout).to_string();
    text.push_str(&String::from_utf8_lossy(&output.stderr));
    (output.status.success(), ms, text)
}

fn verify_bundle(bundle: &Path) -> (bool, f64, String) {
    let exe = example_beside_me("verify-bundle");
    let summary_path = bundle.parent().unwrap().join("verify-summary.json");
    let t = Instant::now();
    let out = std::process::Command::new(exe)
        .args([
            "--bundle", bundle.to_str().unwrap(),
            "--json", summary_path.to_str().unwrap(),
            "--quiet",
        ])
        .output()
        .expect("run verify-bundle");
    let ms = t.elapsed().as_secs_f64() * 1000.0;
    let summary = std::fs::read_to_string(&summary_path).unwrap_or_else(|_| "null".into());
    (out.status.success(), ms, summary)
}

/// Compare every partition of two bundles byte for byte, one at a time.
///
/// Streaming rather than whole-bundle: at ~5.7 GB each, holding both would need more memory than
/// this machine has, and a determinism check that could not run at scale would be the wrong tool
/// for the one measurement that is about scale.
fn compare_partitions(a: &Path, b: &Path) -> (usize, bool, Option<String>) {
    let da = a.join("data");
    let db = b.join("data");
    let list = |d: &Path| -> Result<std::collections::BTreeSet<String>, String> {
        std::fs::read_dir(d)
            .map_err(|e| format!("{}: {e}", d.display()))
            .map(|rd| rd.filter_map(|e| e.ok()).map(|e| e.file_name().to_string_lossy().to_string()).collect())
    };
    // **Name SETS, not A's listing.** Enumerating only A would miss a partition present in B and
    // absent from A -- a difference the determinism row exists to catch.
    let (na, nb) = match (list(&da), list(&db)) {
        (Ok(a), Ok(b)) => (a, b),
        (Err(e), _) | (_, Err(e)) => return (0, false, Some(e)),
    };
    if na != nb {
        let only_a: Vec<_> = na.difference(&nb).cloned().collect();
        let only_b: Vec<_> = nb.difference(&na).cloned().collect();
        return (0, false, Some(format!("partition sets differ: only in A {only_a:?}, only in B {only_b:?}")));
    }
    let names: Vec<String> = na.into_iter().collect();

    let mut compared = 0usize;
    for name in &names {
        let pa = match std::fs::read(da.join(name)) {
            Ok(v) => v,
            Err(e) => return (compared, false, Some(format!("{name}: unreadable in A ({e})"))),
        };
        let pb = match std::fs::read(db.join(name)) {
            Ok(v) => v,
            Err(e) => return (compared, false, Some(format!("{name}: absent from B ({e})"))),
        };
        if pa != pb {
            return (compared, false, Some(format!("{name}: bytes differ")));
        }
        compared += 1;
    }
    (compared, true, None)
}

/// A built binary beside this test binary.
///
/// Derived rather than taken from `CARGO_BIN_EXE_*`, and asserted to exist — the alternative is a
/// harness that silently measures a stale binary, which is the failure `pin-tree.mjs --binaries`
/// exists to catch one level up.
fn binary_beside_me(name: &str) -> PathBuf {
    let me = std::env::current_exe().expect("the test binary knows where it is");
    let profile = me.parent().and_then(|d| d.parent()).expect("target/<profile>/deps/<test>");
    let exe = if cfg!(windows) { format!("{name}.exe") } else { name.to_string() };
    let path = profile.join(&exe);
    assert!(path.exists(), "{name} is not built at {}", path.display());
    path
}

fn example_beside_me(name: &str) -> PathBuf {
    let me = std::env::current_exe().expect("the test binary knows where it is");
    let profile = me.parent().and_then(|d| d.parent()).expect("target/<profile>/deps/<test>");
    let exe = if cfg!(windows) { format!("{name}.exe") } else { name.to_string() };
    let path = profile.join("examples").join(&exe);
    assert!(path.exists(), "the {name} example is not built at {}", path.display());
    path
}
