// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Christopher Donini and the Spatial IDE contributors

//! **The 5 GB scale pass**, as a committed, re-runnable harness.
//!
//! ```bash
//! cargo test --release -p spatial-kernel --test scale_pass -- --ignored --nocapture
//! ```
//!
//! `#[ignore]`d: it generates ~5 GB, publishes ~5.7 GB twice, and runs for the better part of an
//! hour. It refuses to run on a debug build.
//!
//! **Everything it does is pre-registered in `kernel/SCALE-PASS-PREREGISTRATION.md`**, which was
//! committed before this file existed and before the fixture existed. Where a number appears here
//! it is because that file declared it; where a ceiling appears here it is because that file
//! declared it. Changing either after a result has been seen invalidates the run.
//!
//! ## The cold-open row is not here
//!
//! It needs three reboots and an operator. `kernel/scripts/cold-open.ps1` is that phase, and it runs
//! **after** everything in this file — decided with the human before any measurement, because a
//! reboot re-evicts the cache anyway and an operator's window should not be spent on a pass that
//! might invalidate earlier.
//!
//! ## What this harness may and may not be used for
//!
//! - **Every comparison is within-session.** The canary is taken at each phase boundary; a spread
//!   beyond the declared 10 % invalidates that phase.
//! - **No throughput claim.** Bytes and durations are recorded side by side and never divided.
//! - **Nothing here is compared with any earlier section of `kernel/RESULTS.md`.** This fixture has
//!   403 row groups where every earlier one had a single row group, and the confound is declared.
//! - The 145 MB **in-session control** is generated by this same binary in this same session, with
//!   the same `row_group_rows`, and it is the only thing the 5 GB memory figure may be compared
//!   with.

mod support;

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::{Duration, Instant};

use spatial_engine::fixture::{
    write_geoparquet_cancellable, AttributeMode, CrsMode, FixtureFacts, FixtureProgress,
    FixtureSpec, IdentityMode, LicenseMode,
};
use spatial_engine::identity::IdentityDeclaration;
use spatial_engine::{Bbox, CancelToken, Dataset, ViewportQuery};
use support::*;

// ---- Pre-registered, from SCALE-PASS-PREREGISTRATION.md §1a ------------------------------------

const FEATURES: usize = 3_300_000;
const AVG_VERTICES: usize = 100;
const HOLE_EVERY: usize = 7;
const SEED: u64 = 0x5EED_2056_0000_0005;
const CHUNK: usize = 8_192;
const ROW_GROUP_ROWS: usize = 8_192;

/// The in-session control (§6). Same binary, same session, same `row_group_rows` — the second point
/// the "flat with respect to file size" claim needs, since between-session comparison is forbidden.
const CONTROL_FEATURES: usize = 100_000;

// ---- Pre-registered predictions (§1b), asserted rather than recomputed --------------------------

const PREDICTED_RINGS: usize = 3_771_429;
const PREDICTED_ROW_GROUPS: usize = 403;
/// Exact, from the generator's grid: (⌊1817/2⌋+1)².
const QUARTER_ROWS: u64 = 826_281;
/// Exact: (⌊1817/8⌋+1)².
const SIXTY_FOURTH_ROWS: u64 = 51_984;
const GRID_COLS: f64 = 1817.0;
const CELL_M: f64 = 40.0;

// ---- Pre-registered sample counts (§6) ---------------------------------------------------------

const WHOLE_FILE_RUNS: usize = 5;
const VIEWPORT_RUNS: usize = 7;
const CANCEL_TRIALS: usize = 7;

// ---- Pre-registered watchdog ceilings (§3) -----------------------------------------------------

const CEIL_GENERATE: Duration = Duration::from_secs(1800);
const CEIL_GENERATE_CONTROL: Duration = Duration::from_secs(300);
const CEIL_OPEN: Duration = Duration::from_secs(300);
const CEIL_WHOLE_FILE: Duration = Duration::from_secs(900);
const CEIL_VIEWPORT: Duration = Duration::from_secs(600);
const CEIL_CANCEL: Duration = Duration::from_secs(60);
const SILENCE_STREAM: Duration = Duration::from_secs(120);
const SILENCE_GENERATE: Duration = Duration::from_secs(60);

// ---- Pre-registered sampler cadences (§6) ------------------------------------------------------

const CADENCE_SHORT_MS: u64 = 50;
const CADENCE_LONG_MS: u64 = 250;

/// `docs/08`: cancellation acknowledged < 100 ms, **any operation**. No size exemption.
const CANCEL_BUDGET_MS: f64 = 100.0;

fn evidence_dir() -> PathBuf {
    let d = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("target/slice-evidence/scale-pass");
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn fixture_path() -> PathBuf {
    evidence_dir().join("parcels-5gb.parquet")
}

fn control_path() -> PathBuf {
    evidence_dir().join("parcels-control-145mb.parquet")
}

fn spec_5gb() -> FixtureSpec {
    FixtureSpec {
        features: FEATURES,
        avg_vertices: AVG_VERTICES,
        hole_every: HOLE_EVERY,
        seed: SEED,
        crs_mode: CrsMode::DeclaredLv95,
        with_covering_bbox: true,
        chunk: CHUNK,
        row_group_rows: ROW_GROUP_ROWS,
        identity: IdentityMode::NativeUnique,
        attributes: AttributeMode::None,
        // Determinism-critical: a source-declared license needs no `--license-at`, and an
        // operator-declared instant is a semantic input inside ADR-017 §12's determinism surface.
        license: LicenseMode::DeclaredBySource,
    }
}

fn spec_control() -> FixtureSpec {
    FixtureSpec { features: CONTROL_FEATURES, ..spec_5gb() }
}

/// Progress that feeds the watchdog's silence clock and counts chunks.
struct GenProgress<'a> {
    dog: &'a Watchdog,
    chunks: AtomicUsize,
}

impl FixtureProgress for GenProgress<'_> {
    fn chunk_written(&self, _i: usize, written: usize, total: usize, bytes: u64) {
        self.dog.beat();
        let n = self.chunks.fetch_add(1, Ordering::Relaxed);
        if n % 50 == 0 {
            println!("  [generate] {written}/{total} features, {bytes} B");
        }
    }
}

/// SHA-256 of a file, streamed. **Never called at cold time** — see the preregistration §4a.
fn sha256_file(path: &Path) -> std::io::Result<String> {
    use std::io::Read as _;
    let mut f = std::fs::File::open(path)?;
    let mut buf = vec![0u8; 8 << 20];
    let mut all: Vec<u8> = Vec::new();
    // Hashed incrementally would be better; `canonical::sha256_hex` takes a slice, so this reads in
    // blocks and accumulates. At 5 GB that is 5 GB resident for the duration of the hash — which is
    // why this is called in its own phase, never inside a memory measurement.
    loop {
        let n = f.read(&mut buf)?;
        if n == 0 {
            break;
        }
        all.extend_from_slice(&buf[..n]);
    }
    Ok(spatial_renderer::canonical::sha256_hex(&all))
}

/// One streaming run: time to first batch, total time, rows, batches.
struct StreamRun {
    first_batch_ms: f64,
    total_ms: f64,
    rows: u64,
    batches: usize,
}

fn stream_once(ds: &Dataset, q: &ViewportQuery, dog: &Watchdog) -> StreamRun {
    let cancel = CancelToken::new();
    let t0 = Instant::now();
    let mut stream = ds.stream_with_cancel(q, cancel).expect("stream opens");
    let mut payload = Vec::new();
    let mut first: Option<f64> = None;
    let mut rows = 0u64;
    let mut batches = 0usize;

    while let Some(info) = stream.next_into(&mut payload) {
        let info = info.expect("batch");
        if first.is_none() {
            first = Some(t0.elapsed().as_secs_f64() * 1000.0);
        }
        rows += info.rows as u64;
        batches += 1;
        payload.clear();
        dog.beat();
    }
    StreamRun {
        first_batch_ms: first.unwrap_or(f64::NAN),
        total_ms: t0.elapsed().as_secs_f64() * 1000.0,
        rows,
        batches,
    }
}

#[ignore = "measurement harness: ~5 GB of disk, tens of minutes, release-only"]
#[test]
fn measure_the_five_gigabyte_scale_pass() {
    refuse_debug("the 5 GB scale pass");

    let dir = evidence_dir();
    let mut json = String::from("{\n");
    let mut canaries: Vec<Canary> = Vec::new();

    let hardware = json_escape(&hardware_profile());
    let media = json_escape(&media_type());
    println!("hardware: {hardware}");
    println!("media:    {media}");
    json.push_str(&format!("  \"hardware\": \"{hardware}\",\n  \"media_type\": \"{media}\",\n"));
    json.push_str(&format!(
        "  \"preregistration\": \"kernel/SCALE-PASS-PREREGISTRATION.md\",\n  \"cadence_short_ms\": {CADENCE_SHORT_MS},\n  \"cadence_long_ms\": {CADENCE_LONG_MS},\n"
    ));

    canaries.push(Canary::take("start"));

    // ---- Phase 1: the fixtures -----------------------------------------------------------------
    let free_before = require_disk("generate");
    json.push_str(&format!("  \"free_bytes_before\": {free_before},\n"));

    let (facts, gen_ms) = generate(&fixture_path(), &spec_5gb(), CEIL_GENERATE, "generate-5gb");
    let (control_facts, control_gen_ms) = generate(
        &control_path(),
        &spec_control(),
        CEIL_GENERATE_CONTROL,
        "generate-control",
    );

    // **Predictions asserted, not recomputed.** A mismatch here is an instrument failure and stops
    // the pass; it is not a machine fact to be reported as a result.
    assert_eq!(facts.features, FEATURES, "the generator wrote a different feature count");
    assert_eq!(facts.rings, PREDICTED_RINGS, "ring count differs from the pre-registered prediction");
    assert!(
        (4.0e9..=6.5e9).contains(&(facts.bytes as f64)),
        "fixture is {} B, outside the pre-registered 4.0–6.5 GB regeneration band",
        facts.bytes
    );

    let fixture_sha = sha256_file(&fixture_path()).expect("hash the fixture");
    println!("fixture sha256: {fixture_sha}");

    json.push_str(&format!(
        "  \"fixture\": {{\"path\": \"parcels-5gb.parquet\", \"sha256\": \"{fixture_sha}\", \
         \"features\": {}, \"vertices\": {}, \"rings\": {}, \"bytes\": {}, \
         \"min_vertices\": {}, \"max_vertices\": {}, \"coord_bits_xor\": \"{:#018x}\", \
         \"extent\": [{:.3}, {:.3}, {:.3}, {:.3}], \"wall_ms\": {:.1}, \
         \"predicted_vertices\": 345414000, \"predicted_rings\": {PREDICTED_RINGS}, \
         \"predicted_bytes\": 5009600000, \"predicted_row_groups\": {PREDICTED_ROW_GROUPS}}},\n",
        facts.features, facts.vertices, facts.rings, facts.bytes,
        facts.min_vertices_per_feature, facts.max_vertices_per_feature, facts.coord_bits_xor,
        facts.extent[0], facts.extent[1], facts.extent[2], facts.extent[3], gen_ms
    ));
    json.push_str(&format!(
        "  \"control_fixture\": {{\"features\": {}, \"vertices\": {}, \"bytes\": {}, \"wall_ms\": {:.1}}},\n",
        control_facts.features, control_facts.vertices, control_facts.bytes, control_gen_ms
    ));
    canaries.push(Canary::take("after-generate"));

    // ---- Phase 2: warm open, and the identity scan isolated by A/B ------------------------------
    require_disk("open");
    let (open_full_ms, open_prelude_ms) = open_ab(&fixture_path());
    let scan_ms = open_full_ms - open_prelude_ms;
    println!(
        "open: full {open_full_ms:.1} ms | prelude-only {open_prelude_ms:.1} ms | scan {scan_ms:.1} ms"
    );
    json.push_str(&format!(
        "  \"warm_open\": {{\"full_ms\": {open_full_ms:.3}, \"prelude_only_ms\": {open_prelude_ms:.3}, \
         \"identity_scan_ms\": {scan_ms:.3}, \"basis\": \"A/B on two product paths \
         (skip_uniqueness_check true/false), same session, same binary\"}},\n"
    ));
    canaries.push(Canary::take("after-open"));

    // ---- Phase 3: streaming ---------------------------------------------------------------------
    require_disk("stream");
    let ds = Dataset::open(fixture_path()).expect("open the 5 GB fixture");

    let whole = ViewportQuery { bbox: None, bbox_crs: None, limit: None };
    let (whole_first, whole_total, whole_rows, whole_batches, whole_mem) =
        stream_phase(&ds, &whole, WHOLE_FILE_RUNS, CEIL_WHOLE_FILE, "whole-file");
    assert_eq!(whole_rows, FEATURES as u64, "the whole-file stream did not return every row");

    let e_lo = spatial_engine::fixture::E_LO;
    let n_lo = spatial_engine::fixture::N_LO;
    let quarter = ViewportQuery {
        bbox: Some(Bbox {
            xmin: e_lo,
            ymin: n_lo,
            xmax: e_lo + GRID_COLS / 2.0 * CELL_M,
            ymax: n_lo + GRID_COLS / 2.0 * CELL_M,
        }),
        bbox_crs: None,
        limit: None,
    };
    let (q_first, q_total, q_rows, q_batches, _) =
        stream_phase(&ds, &quarter, VIEWPORT_RUNS, CEIL_VIEWPORT, "quarter");

    let sixty_fourth = ViewportQuery {
        bbox: Some(Bbox {
            xmin: e_lo,
            ymin: n_lo,
            xmax: e_lo + GRID_COLS / 8.0 * CELL_M,
            ymax: n_lo + GRID_COLS / 8.0 * CELL_M,
        }),
        bbox_crs: None,
        limit: None,
    };
    let (s_first, s_total, s_rows, s_batches, _) =
        stream_phase(&ds, &sixty_fourth, VIEWPORT_RUNS, CEIL_VIEWPORT, "sixty-fourth");

    // **The strongest instrument check in the pass.** These are pure arithmetic over the
    // generator's grid; a mismatch means the filter or the generator is wrong, not that the
    // machine drifted. Recorded rather than asserted, because the covering-bbox filter is
    // conservative by design (it selects candidates whose bbox intersects), so the exact identity
    // is a prediction about the *grid*, and any difference is a finding worth reporting in full.
    println!("quarter rows {q_rows} (predicted {QUARTER_ROWS}); 1/64 rows {s_rows} (predicted {SIXTY_FOURTH_ROWS})");

    json.push_str(&format!(
        "  \"streaming\": {{\
         \"whole_file\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {whole_rows}, \"batches\": {whole_batches}}},\
         \"quarter\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {q_rows}, \"predicted_rows\": {QUARTER_ROWS}, \"batches\": {q_batches}}},\
         \"sixty_fourth\": {{\"first_batch\": {}, \"total\": {}, \"rows\": {s_rows}, \"predicted_rows\": {SIXTY_FOURTH_ROWS}, \"batches\": {s_batches}}}}},\n",
        summarize("whole-file first batch", &whole_first),
        summarize("whole-file total", &whole_total),
        summarize("quarter first batch", &q_first),
        summarize("quarter total", &q_total),
        summarize("1/64 first batch", &s_first),
        summarize("1/64 total", &s_total),
    ));
    canaries.push(Canary::take("after-streaming"));

    // ---- Phase 4: the memory row, with its in-session control -----------------------------------
    let control_ds = Dataset::open(control_path()).expect("open the control fixture");
    let (_, _, _, _, control_mem) =
        stream_phase(&control_ds, &whole, 1, CEIL_WHOLE_FILE, "control-whole-file");

    let peak_5gb = whole_mem.iter().copied().max().unwrap_or(0);
    let peak_control = control_mem.iter().copied().max().unwrap_or(0);
    println!("private commit peak: 5 GB {peak_5gb} B | 145 MB control {peak_control} B");
    json.push_str(&format!(
        "  \"memory\": {{\"peak_private_commit_5gb\": {peak_5gb}, \
         \"peak_private_commit_control\": {peak_control}, \
         \"declared_composed_bound_bytes\": 83886080, \
         \"caveat\": \"process private commit is NOT the bounded quantity. DuckDB's own streaming \
         buffer sits outside every declared bound by design. The bounded claim is the data-plane \
         window; these two figures are the two points the flatness statement needs, same session, \
         same binary.\"}},\n"
    ));
    canaries.push(Canary::take("after-memory"));

    // ---- Phase 5: cancellation mid-stream at scale ----------------------------------------------
    require_disk("cancel");
    let cancel_samples = cancel_phase(&ds, &whole);
    let cs = sorted(&cancel_samples);
    let cancel_max = cs.last().copied().unwrap_or(f64::NAN);
    println!(
        "cancellation: n={} p50 {:.2} ms p95 {:.2} ms max {:.2} ms (budget {CANCEL_BUDGET_MS} ms)",
        cs.len(),
        pct(&cs, 0.5),
        pct(&cs, 0.95),
        cancel_max
    );
    json.push_str(&format!(
        "  \"cancellation_mid_stream\": {{\"summary\": {}, \"budget_ms\": {CANCEL_BUDGET_MS}, \"max_ms\": {cancel_max:.3}}},\n",
        summarize("cancel mid-stream at 5 GB", &cancel_samples)
    ));
    canaries.push(Canary::take("after-cancel"));

    // ---- Close out -------------------------------------------------------------------------------
    let (spread, canary_ok) = canary_spread(&canaries);
    let free_after = free_bytes_on_c().unwrap_or(0);
    let points: Vec<String> = canaries.iter().map(Canary::json).collect();
    json.push_str(&format!(
        "  \"canary\": {{\"points\": [{}], \"long_min_spread\": {spread:.4}, \"declared_max_spread\": {CANARY_MAX_SPREAD}, \"within_declared\": {canary_ok}}},\n",
        points.join(", ")
    ));
    json.push_str(&format!("  \"free_bytes_after\": {free_after},\n"));
    json.push_str("  \"note\": \"Publish, determinism and strict-reader phases are driven by kernel/scripts/run-scale-publish.mjs against the same frozen binaries; the cold-open row is kernel/scripts/cold-open.ps1 and runs last.\"\n}\n");

    let artifact = dir.join("scale-pass.json");
    std::fs::write(&artifact, &json).expect("write the evidence artifact");
    println!("artifact: {}", artifact.display());

    // **Asserted last, so the artifact exists either way.** A phase whose canary moved is recorded
    // with its invalidator named rather than silently dropped.
    assert!(
        canary_ok,
        "canary spread {spread:.4} exceeds the declared {CANARY_MAX_SPREAD} — the machine moved \
         underneath these numbers and the run is invalidated"
    );
}

/// Generate one fixture under a declared ceiling, returning its facts and wall time.
fn generate(
    path: &Path,
    spec: &FixtureSpec,
    ceiling: Duration,
    phase: &'static str,
) -> (FixtureFacts, f64) {
    // **Refused rather than reused, and the reason is not tidiness.** `FixtureFacts` are what the
    // *writer* measured while writing — vertices, rings, the coordinate XOR, the extent — and none
    // of them can be recovered from a finished file without re-reading and re-deriving them, which
    // would be a second implementation of the generator's own accounting. A reuse path would have
    // to fabricate the facts this pass records beside its predictions.
    assert!(
        !path.exists(),
        "{} already exists. This pass generates once and records the facts from that generation. \
         Remove the file to re-run the phase — deliberately manual, because it is 5 GB.",
        path.display()
    );

    let cancel = CancelToken::new();
    let dog = Watchdog::start(phase, ceiling, Some(SILENCE_GENERATE), cancel.clone());
    let progress = GenProgress { dog: &dog, chunks: AtomicUsize::new(0) };

    let t0 = Instant::now();
    let facts = write_geoparquet_cancellable(path, spec, &cancel, Some(&progress))
        .expect("fixture generation");
    let ms = t0.elapsed().as_secs_f64() * 1000.0;
    let fired = dog.finish();
    assert!(!fired, "the {phase} watchdog fired; this phase is unmeasured and is not re-run");

    // Wall time and bytes side by side, deliberately not divided.
    println!("[{phase}] {} features, {} B, {ms:.0} ms", facts.features, facts.bytes);
    (facts, ms)
}

/// Open the dataset twice on two product paths, so the identity scan is a *difference* rather than
/// an inference. Returns (full open ms, prelude-only ms).
fn open_ab(path: &Path) -> (f64, f64) {
    let cancel = CancelToken::new();
    let dog = Watchdog::start("open-ab", CEIL_OPEN, None, cancel);

    let t0 = Instant::now();
    let full = Dataset::open(path).expect("open with the uniqueness scan");
    let full_ms = t0.elapsed().as_secs_f64() * 1000.0;
    drop(full);

    let mut declared = IdentityDeclaration::new("id", "scale-pass", "2026-08-07T00:00:00Z");
    declared.skip_uniqueness_check = true;
    let t1 = Instant::now();
    let prelude = Dataset::open_with_declared_identity(path, declared, &CancelToken::new())
        .expect("open with the scan skipped");
    let prelude_ms = t1.elapsed().as_secs_f64() * 1000.0;
    drop(prelude);

    assert!(!dog.finish(), "the open watchdog fired; this phase is unmeasured");
    (full_ms, prelude_ms)
}

/// n runs of one query, under a declared ceiling, with private commit sampled throughout.
#[allow(clippy::type_complexity)]
fn stream_phase(
    ds: &Dataset,
    q: &ViewportQuery,
    runs: usize,
    ceiling: Duration,
    phase: &'static str,
) -> (Vec<f64>, Vec<f64>, u64, usize, Vec<usize>) {
    let cancel = CancelToken::new();
    let dog = Watchdog::start(phase, ceiling, Some(SILENCE_STREAM), cancel);
    let sampler = MemorySampler::start(CADENCE_LONG_MS);

    let mut first = Vec::with_capacity(runs);
    let mut total = Vec::with_capacity(runs);
    let (mut rows, mut batches) = (0u64, 0usize);

    for i in 0..runs {
        let r = stream_once(ds, q, &dog);
        println!(
            "  [{phase}] run {}/{runs}: first batch {:.1} ms, total {:.1} ms, {} rows, {} batches",
            i + 1,
            r.first_batch_ms,
            r.total_ms,
            r.rows,
            r.batches
        );
        first.push(r.first_batch_ms);
        total.push(r.total_ms);
        rows = r.rows;
        batches = r.batches;
    }

    let samples = sampler.finish();
    assert!(!dog.finish(), "the {phase} watchdog fired; this phase is unmeasured and is not re-run");
    (first, total, rows, batches, samples)
}

/// Cancellation mid-stream, producer-observed, in one process so both observations share a clock.
fn cancel_phase(ds: &Dataset, q: &ViewportQuery) -> Vec<f64> {
    let mut samples = Vec::with_capacity(CANCEL_TRIALS);

    for trial in 0..CANCEL_TRIALS {
        let cancel = CancelToken::new();
        let dog = Watchdog::start("cancel", CEIL_CANCEL, None, cancel.clone());
        let sampler = MemorySampler::start(CADENCE_SHORT_MS);

        let mut stream = ds.stream_with_cancel(q, cancel.clone()).expect("stream opens");
        let mut payload = Vec::new();

        // Let the stream reach steady state before cancelling — a cancel issued before the first
        // batch measures a different thing, and that case has its own coverage in the ordinary
        // suite. Two batches is enough at this size and keeps the trial short.
        let mut seen = 0;
        while seen < 2 {
            match stream.next_into(&mut payload) {
                Some(Ok(_)) => {
                    seen += 1;
                    payload.clear();
                }
                Some(Err(e)) => panic!("stream failed before cancellation: {e}"),
                None => break,
            }
        }

        let t = Instant::now();
        cancel.cancel();
        // Producer-observed acknowledgement: drain until the stream reports it is over.
        while let Some(r) = stream.next_into(&mut payload) {
            payload.clear();
            if r.is_err() {
                break;
            }
        }
        let ms = t.elapsed().as_secs_f64() * 1000.0;
        samples.push(ms);
        println!("  [cancel] trial {}/{CANCEL_TRIALS}: {ms:.2} ms", trial + 1);

        let _ = sampler.finish();
        assert!(!dog.finish(), "the cancel watchdog fired on trial {trial}");
    }
    samples
}

// ================================================================================================
// Phases 6-9: publish at scale, determinism, and strict-reader verification
// ================================================================================================

/// **The class-3 boundary's first real workout**, plus determinism and verification.
///
/// A separate `#[ignore]`d test from the streaming phases, for one reason: it needs the fixture the
/// first test generates, and splitting them lets the operator re-run the publish half without
/// regenerating 5 GB. It refuses to run if the fixture is absent rather than generating one, so the
/// two halves can never disagree about which file they measured.
///
/// ## Why the CLI, and why not for cancellation
///
/// Publishes A and B go through `publish-bundle` — the sanctioned `--approve` path, exercising the
/// composition root an operator actually runs. Cancellation does **not**: a threshold asserted
/// across a process boundary measures scheduling, not the property, so cancellation cells belong
/// in-process where both observations share one clock. They are covered by the ordinary suite's
/// boundary tests and by the mid-stream cells above; a *publish* cancellation cell at 5 GB is
/// registered in the preregistration and is driven separately, because aiming at a phase requires
/// the in-process progress observer.
///
/// ## The grant is self-minted, and that is disclosed rather than hidden
///
/// The human's F-5 ruling binds a future **exposure surface**: the requester must never mint the
/// grant. A harness invoked from the operator's own shell against developer/test tooling is the
/// operator's hand, not a requester. Every publish nonetheless passes `--grant-destination`, the
/// only non-tautological part of a self-minted grant, so at least one scope member is checked
/// against a resolved fact.
#[ignore = "measurement harness: publishes ~5.7 GB twice, release-only; needs the fixture from the streaming phase"]
#[test]
fn measure_publish_at_five_gigabytes() {
    refuse_debug("the 5 GB publish pass");
    let dir = evidence_dir();
    let fixture = fixture_path();
    assert!(
        fixture.exists(),
        "the 5 GB fixture is absent at {}. Run `measure_the_five_gigabyte_scale_pass` first; this \
         phase deliberately does not generate one, so the two halves cannot measure different files.",
        fixture.display()
    );

    require_disk("publish");
    let mut canaries = vec![Canary::take("publish-start")];
    let mut json = String::from("{\n");

    // The audit log for this run only — never the operator's real one. Preregistration section 5c.
    let audit_dir = dir.join("audit");
    let _ = std::fs::remove_dir_all(&audit_dir);
    std::fs::create_dir_all(&audit_dir).unwrap();
    let audit_log = audit_dir.join("publish.jsonl");
    assert!(!audit_log.exists(), "the audit log must start absent for the record-count assertions");

    // A destination that cannot trip F-3's bare-word credential needles. Checked before the run,
    // because a destination containing `secret`/`password`/`apikey`/`credential` refuses the
    // publish with NO audit record at all, which would look like a publish failure.
    let bundle_dir = dir.join("bundles");
    std::fs::create_dir_all(&bundle_dir).unwrap();
    let dest_lower = bundle_dir.to_string_lossy().to_ascii_lowercase();
    for needle in ["credential", "password", "passwd", "secret", "api_key", "apikey"] {
        assert!(
            !dest_lower.contains(needle),
            "the bundle destination contains `{needle}`, which the audit record's docs/09 scan \
             treats as a credential — the publish would refuse with no record written"
        );
    }

    let style_path = dir.join("scale-style.json");
    std::fs::write(&style_path, SCALE_STYLE).unwrap();
    let viewer_dir = dir.join("viewer");
    std::fs::create_dir_all(&viewer_dir).unwrap();
    std::fs::write(viewer_dir.join("index.html"), b"<!doctype html><title>scale</title>").unwrap();
    std::fs::write(viewer_dir.join("NOTICE.txt"), b"stub notice\n").unwrap();

    // ---- Publish A -------------------------------------------------------------------------------
    let a = bundle_dir.join("bundle-a");
    let (a_ok, a_ms, a_out) = publish_via_cli(&fixture, &style_path, &viewer_dir, &a, &audit_log);
    assert!(a_ok, "publish A failed:\n{a_out}");
    println!("[publish A] {a_ms:.0} ms");
    canaries.push(Canary::take("after-publish-a"));

    // ---- Publish B, to a different destination ----------------------------------------------------
    //
    // A different `--out`, because re-publish over an existing destination is a typed refusal — and
    // that is a *bonus*: ADR-017 section 13 forbids any local path in a bundle, so two different
    // destinations must still produce a byte-identical manifest. A stronger determinism check than
    // one destination could give.
    require_disk("publish-b");
    let b = bundle_dir.join("bundle-b");
    let (b_ok, b_ms, b_out) = publish_via_cli(&fixture, &style_path, &viewer_dir, &b, &audit_log);
    assert!(b_ok, "publish B failed:\n{b_out}");
    println!("[publish B] {b_ms:.0} ms");
    canaries.push(Canary::take("after-publish-b"));

    // ---- Determinism -------------------------------------------------------------------------------
    let manifest_a = sha256_file(&a.join("manifest.json")).unwrap();
    let manifest_b = sha256_file(&b.join("manifest.json")).unwrap();
    let manifests_identical = manifest_a == manifest_b;

    let (partitions_compared, partitions_identical, first_difference) = compare_partitions(&a, &b);
    println!(
        "determinism: manifests {} | {partitions_compared} partitions compared, identical={partitions_identical}",
        if manifests_identical { "identical" } else { "DIFFER" }
    );

    json.push_str(&format!(
        "  \"publish\": {{\"a_wall_ms\": {a_ms:.1}, \"b_wall_ms\": {b_ms:.1}, \
         \"manifest_sha256_a\": \"{manifest_a}\", \"manifest_sha256_b\": \"{manifest_b}\", \
         \"manifests_identical\": {manifests_identical}, \
         \"partitions_compared\": {partitions_compared}, \
         \"partitions_identical\": {partitions_identical}, \
         \"first_difference\": {:?}}},\n",
        first_difference.as_deref().unwrap_or("")
    ));

    // ---- Strict-reader verification ------------------------------------------------------------------
    let (v_ok, v_ms, v_summary) = verify_bundle(&a);
    println!("[verify] bundle A: ok={v_ok} in {v_ms:.0} ms");
    json.push_str(&format!(
        "  \"strict_reader\": {{\"verified\": {v_ok}, \"wall_ms\": {v_ms:.1}, \"summary\": {v_summary}}},\n"
    ));

    // ---- The audit record ------------------------------------------------------------------------------
    let audit_text = std::fs::read_to_string(&audit_log).expect("the audit log exists");
    let lines: Vec<&str> = audit_text.lines().filter(|l| !l.trim().is_empty()).collect();
    let mut intents = 0usize;
    let mut outcomes = 0usize;
    let mut manifest_hashes: Vec<String> = Vec::new();
    for l in &lines {
        let v: serde_json::Value = serde_json::from_str(l).expect("every audit line parses");
        assert_eq!(v["schema"], "spatial-audit/1", "unexpected audit schema");
        match v["phase"].as_str() {
            Some("intent") => intents += 1,
            Some("outcome") => {
                outcomes += 1;
                if let Some(h) = v["manifest_hash"].as_str() {
                    manifest_hashes.push(h.to_string());
                }
            }
            other => panic!("unexpected audit phase {other:?}"),
        }
    }
    println!("[audit] {} lines, {intents} intent, {outcomes} outcome", lines.len());
    assert_eq!(intents, outcomes, "every attempt must have both records");
    assert_eq!(intents, 2, "two publishes reached the gate");
    assert_eq!(manifest_hashes.len(), 2, "both successes record a manifest hash");
    assert_eq!(
        manifest_hashes[0], manifest_hashes[1],
        "the audit's two manifest hashes differ, so determinism fails at the record level"
    );
    assert_eq!(
        manifest_hashes[0], manifest_a,
        "the audit's manifest hash disagrees with the file on disk"
    );

    json.push_str(&format!(
        "  \"audit\": {{\"lines\": {}, \"intents\": {intents}, \"outcomes\": {outcomes}, \
         \"manifest_hash_matches_disk\": true, \
         \"log\": \"target/slice-evidence/scale-pass/audit/publish.jsonl\"}},\n",
        lines.len()
    ));

    let (spread, canary_ok) = canary_spread(&canaries);
    let points: Vec<String> = canaries.iter().map(Canary::json).collect();
    json.push_str(&format!(
        "  \"canary\": {{\"points\": [{}], \"long_min_spread\": {spread:.4}, \"within_declared\": {canary_ok}}}\n}}\n",
        points.join(", ")
    ));
    std::fs::write(dir.join("scale-publish.json"), &json).unwrap();

    // Asserted after the artifact is written, so a failure is still evidenced.
    assert!(manifests_identical, "ADR-017 determinism FAILED at 5 GB: the two manifests differ");
    assert!(partitions_identical, "partitions differ between two publishes of one request");
    assert!(v_ok, "the strict reader refused the bundle this pass published");
    assert!(canary_ok, "canary spread {spread:.4} exceeds the declared bound");
}

const SCALE_STYLE: &str = r##"{
  "style_version": 1,
  "layer": {
    "geometry": "polygon",
    "fill_color": {"literal": "#aa3333"},
    "fill_opacity": {"literal": 0.8},
    "outline_color": {"literal": "#202020"},
    "outline_width": {"literal": 1.0}
  }
}"##;

/// Run the real `publish-bundle`, through the sanctioned approval path.
fn publish_via_cli(
    data: &Path,
    style: &Path,
    viewer: &Path,
    out: &Path,
    audit_log: &Path,
) -> (bool, f64, String) {
    let exe = binary_beside_me("publish-bundle");
    let approve = out.file_name().unwrap().to_string_lossy().to_string();
    let grant_dir = out.parent().unwrap();

    let t = Instant::now();
    let output = std::process::Command::new(exe)
        .env("SPATIAL_IDE_AUDIT_LOG", audit_log)
        .args([
            "--data", data.to_str().unwrap(),
            "--style", style.to_str().unwrap(),
            "--viewer", viewer.to_str().unwrap(),
            "--out", out.to_str().unwrap(),
            "--approve", &approve,
            // The one part of a self-minted grant that is not a tautology.
            "--grant-destination", grant_dir.to_str().unwrap(),
            // The CLI pins a 5 GB source before the boundary runs; the 300 s default would be tight.
            "--grant-ttl", "900",
            "--viewer-program", "Spatial IDE bundle viewer",
            "--viewer-copyright", "Copyright (C) 2026 the Spatial IDE contributors",
            "--viewer-license", "AGPL-3.0-or-later",
            "--viewer-notice", "NOTICE.txt",
            "--corresponding-source-url", "https://example.invalid/spatial-ide",
        ])
        .output()
        .expect("run publish-bundle");
    let ms = t.elapsed().as_secs_f64() * 1000.0;
    let mut text = String::from_utf8_lossy(&output.stdout).to_string();
    text.push_str(&String::from_utf8_lossy(&output.stderr));
    (output.status.success(), ms, text)
}

fn verify_bundle(bundle: &Path) -> (bool, f64, String) {
    let exe = example_beside_me("verify-bundle");
    let summary_path = bundle.parent().unwrap().join("verify-summary.json");
    let t = Instant::now();
    let out = std::process::Command::new(exe)
        .args([
            "--bundle", bundle.to_str().unwrap(),
            "--json", summary_path.to_str().unwrap(),
            "--quiet",
        ])
        .output()
        .expect("run verify-bundle");
    let ms = t.elapsed().as_secs_f64() * 1000.0;
    let summary = std::fs::read_to_string(&summary_path).unwrap_or_else(|_| "null".into());
    (out.status.success(), ms, summary)
}

/// Compare every partition of two bundles byte for byte, one at a time.
///
/// Streaming rather than whole-bundle: at ~5.7 GB each, holding both would need more memory than
/// this machine has, and a determinism check that could not run at scale would be the wrong tool
/// for the one measurement that is about scale.
fn compare_partitions(a: &Path, b: &Path) -> (usize, bool, Option<String>) {
    let da = a.join("data");
    let db = b.join("data");
    let mut names: Vec<String> = match std::fs::read_dir(&da) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect(),
        Err(e) => return (0, false, Some(format!("bundle A has no data directory: {e}"))),
    };
    names.sort();

    let mut compared = 0usize;
    for name in &names {
        let pa = match std::fs::read(da.join(name)) {
            Ok(v) => v,
            Err(e) => return (compared, false, Some(format!("{name}: unreadable in A ({e})"))),
        };
        let pb = match std::fs::read(db.join(name)) {
            Ok(v) => v,
            Err(e) => return (compared, false, Some(format!("{name}: absent from B ({e})"))),
        };
        if pa != pb {
            return (compared, false, Some(format!("{name}: bytes differ")));
        }
        compared += 1;
    }
    (compared, true, None)
}

/// A built binary beside this test binary.
///
/// Derived rather than taken from `CARGO_BIN_EXE_*`, and asserted to exist — the alternative is a
/// harness that silently measures a stale binary, which is the failure `pin-tree.mjs --binaries`
/// exists to catch one level up.
fn binary_beside_me(name: &str) -> PathBuf {
    let me = std::env::current_exe().expect("the test binary knows where it is");
    let profile = me.parent().and_then(|d| d.parent()).expect("target/<profile>/deps/<test>");
    let exe = if cfg!(windows) { format!("{name}.exe") } else { name.to_string() };
    let path = profile.join(&exe);
    assert!(path.exists(), "{name} is not built at {}", path.display());
    path
}

fn example_beside_me(name: &str) -> PathBuf {
    let me = std::env::current_exe().expect("the test binary knows where it is");
    let profile = me.parent().and_then(|d| d.parent()).expect("target/<profile>/deps/<test>");
    let exe = if cfg!(windows) { format!("{name}.exe") } else { name.to_string() };
    let path = profile.join("examples").join(&exe);
    assert!(path.exists(), "the {name} example is not built at {}", path.display());
    path
}
